### ISSUE TITLE
How to build this project

### ISSUE THREAD

**Issue by constantine97a** [open-rpa/openrpa#112]
Hi 
I found this project ,but I had already look over almost file but I fail to find any materials and words to build this project.

Expect the answer!

Thanks

**Comment by skadefro** [comment]
It would be easyer to answer your request if you could describe what your problem is, what error messages are you getting, what version of os are you using, what version of visual studio etc. What have tried to fix.? 
Again, more information 
Your welcome

**Comment by lcl101** [comment]
Visual Studio 2017

**Comment by skadefro** [comment]
Hey
I honestly don't know what to reply to this. I need an error, a screenshot, anything that explains what the problem is ?
clone it, open the .sln file, make sure OpenRPA is set as startup project and press F5 ?
If you need OCR as well, right click OpenRPA.Image and compile it first.

**Comment by lcl101** [comment]
Emgu CV is not able to detect the project type, unloading and reloading the project may fix this problem. If you are still having difficulty, please send an email to support@emgu.com	OpenRPA.Image

**Comment by skadefro** [comment]
That is not an OpenRPA issue then. I [found this](https://github.com/emgucv/emgucv/blob/master/platforms/nuget/Emgu.CV.targets) googling the error, so a guess would be you either have not installed WPF/WinForms in visual studio, or are changed the build target from the default x64 ?

**Comment by skadefro** [comment]
a side note. the OpenRPA.Image project is not included as a reference to OpenRPA so you can just compile without it ( or just remove it completely ) if you don't need image recognition or OCR

**Comment by burque505** [comment]
This may well be overly basic, and I apologize in advance if it is, but you'll have to go to Tools -> NuGet Package Manager -> Manage NuGet Packages for Solution. It 'should' say some packages are missing and ask you to restore them. It definitely won't build unless you do that. As @lcl101 points out, the first time you build you'll get a message from Emgu CV about the project type.  


![emgu](https://user-images.githubusercontent.com/46876254/62824368-ec276900-bb59-11e9-8291-d24f40f85e1f.PNG)
Save, close, reopen. Build (NOT rebuild). I have to do this for every build. 

![success](https://user-images.githubusercontent.com/46876254/62824389-20028e80-bb5a-11e9-8138-fd052cae0851.PNG)

Using VS 2019 CE at the moment, but works the same for VS 2017.

**Comment by skadefro** [comment]
No respone in a while. 
Feel free to comment again, if you still need help
