### ISSUE TITLE
The Native Messaging protocol 's length field is byte[] length instead of char[] length

### ISSUE THREAD

**Issue by constantine97a** [open-rpa/openrpa#125]
https://github.com/open-rpa/openrpa/blob/aae0a8f421d08db7672a32b045d2d05522220ad5/OpenRPA.NativeMessagingHost/Program.cs#L137

**Comment by skadefro** [comment]
Did you experience any errors ?
Do you have an example i can reproduce that shows an error parsing messages in NM ?

**Comment by skadefro** [comment]
I'm not sure what to do with this. Feel free to send a pull request, or point out where you think the change should be, and i will test and implement it.
