### ISSUE TITLE
Installing Open RPA

### ISSUE THREAD

**Issue by karthikshashi** [open-rpa/openrpa#126]
Hi. The tool that you have taken initiative to develop is very promising and thanks to you for that. I have a quick question if I can get a copy of a step by step install guide if available. It will be of great help !!!

Thanks and have a great day.

**Comment by skadefro** [comment]
There is no installer at the moment. you just download the binaries and run it.
so.
1) go to https://github.com/open-rpa/openrpa/releases and download http://OpenRPA.Updater.zip
2) unzip it somewhere and call OpenRPA.Updater.exe and answer yes
![image](https://user-images.githubusercontent.com/4155937/65224961-83220200-dac4-11e9-8dc0-c56bbbdbb4f7.png)
Then you can start the robot openrpa.exe placed in the rpa subfolder, or use the launch button from inside the updater
![image](https://user-images.githubusercontent.com/4155937/65225069-b6fd2780-dac4-11e9-8f80-322e1b9ac21f.png)

**Comment by burque505** [comment]
The Updater no longer functions for me on Win7 in any meaningful sense. I have been able to connect and use OpenRPA for months now, but now after updating today (or trying to) I cannot connect on Win7. 

On Win10, OpenRPA simply does not update (e.g. Snippets package is missing; new packages visible from Win7 updater do not appear), but I can, at least, still connect. 

I have provided details in the Slack and by email. Following a complete reinstall:

![image](https://user-images.githubusercontent.com/46876254/65294189-1f76f380-db1b-11e9-9381-88ae2eac8aa1.png)
(Unable to connect, Win7)
![no project available](https://user-images.githubusercontent.com/46876254/65294348-8f857980-db1b-11e9-9aff-97996aa1e221.PNG)
(No projects can be created)

**Comment by karthikshashi** [comment]
Hello Allan, There's no such exe file in the downloaded package.

I can only see an OpenRPA.Updater.csproj file. Should I rename this to .exe
and try again?

**Comment by skadefro** [comment]
Then you downloaded the wrong file, you downloaded the source code, you need to download OpenRPA.Updater.zip ( right now that is https://github.com/open-rpa/openrpa/releases/download/1.0.19/OpenRPA.Updater.zip )

**Comment by karthikshashi** [comment]
I'm facing the same issue. Not able to connect to demo1.openrpa....

**Comment by burque505** [comment]
@karthikshashi, are you on Win10 or Win7? @skadefro cleared up the Win10 issue I had (just delete layout.config and restart), and OpenRPA is working great on Win10.

**Comment by burque505** [comment]
I have a possible solution for the OP's issue - **now running fine on Win10 and Win7**.
1) I deleted my OpenRPA directory, re-downloaded the OpenRPAUpdater.zip that @skadefro referenced above.
2) I ran the Updater (not as Administrator, although I am an admin user) from a sub-folder of C:\ ("C:\OpenRPA-root").
3) I waited until a popup appeared asking if I wanted to install OpenRPA and the most common packages, to which I agreed.
4) The download was quite fast. I then signed in, following the prompt, with my previous name and password.
5) All my existing workflows were restored. The new Snippets functionality is present and working.

**Comment by skadefro** [comment]
@karthikshashi What country are you in ? demo1.openrpa.dk is hosted i google, so if you are located in China then you cannot connect. Then the solution is to work offline.
Open settings.json and remove the URI in wsurl 
![image](https://user-images.githubusercontent.com/4155937/65345837-7c39e300-dbdb-11e9-9fcb-b6ff4948e42c.png)
if you are NOT in china, would it be possible for me to see your installation using teamviewer ?

**Comment by skadefro** [comment]
So a about a week ago, nuget updated the API with a new search function for version 3. But they broke the version 2 API in the process. I see a few issues reported in the github repository, but no solution or timeframe for a fix. So while we wait on that ( or i update my code to use V3 ) i created a temporary fix'ed updater, that only check for specific packages.

**Comment by skadefro** [comment]
I am assuming this has been solved, if not, then feel free to reopen this issue
