### ISSUE TITLE
build this project  error

### ISSUE THREAD

**Issue by js0007** [open-rpa/openrpa#128]
Hi

build this project ：

C:\windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets(419,45): error MSB4057: There is no target "Core Compile" in this project

Expect the answer!

Thanks

**Comment by skadefro** [comment]
I really need more information to troubleshoot that, A google search on that error does not give a lot of hits. And I am using the codebase on from both VS 2017 and VS 2019 without any issues.

**Comment by js0007** [comment]
I compiled successfully using vs2019
Thanks
