### ISSUE TITLE
Copy and Paste

### ISSUE THREAD

**Issue by PhilipeTakeo** [open-rpa/openrpa#137]
Hi.
How can I copy and paste?

I'm using CopyClipboard and InsertClipboard activities. The workflow is to open a browser, navigate to Google, search for "wiki itsm" and click on wiki page.
When the page is opened, I use the GetElement activity to select the text and inside GetElement I use CopyClipboard.
After that, I open an App "notes" and use the InsertClipboard activity. But It doesn't work, I attached the Xaml file.

[OpenWikiCopyTextAndPaste.zip](https://github.com/open-rpa/openrpa/files/3816009/OpenWikiCopyTextAndPaste.zip)

**Comment by skadefro** [comment]
Hi Philipe
Theres a few things with the workflow.
1) First of all, there is a mix of GetElement using windows and GetElement using NM, that is proberly giving you some of the issues, you need to keep it "clean" and only use NM
( getapplication is using windows, not NM, the getelement on the wiki page is using windows as well )
2) Secondly, OpenRPA will per default do virtual clicks, so a click in a browser will only affect things like opening a link, it will not set focus or select text. And you removed to "clickelement" and inserted CopyClipboard, so your getting an element but not using it for anything.
3) CopyClipboard will only work if some text is selected, but your not selecting anything, also, you need to save the result some where, you have no variable set in Result on CopyClipboard
4) You don't really need to use CopyClipboard, it would be alot better to get the value directly using GetElement and then assign the text using item.Value, like so:
![image](https://user-images.githubusercontent.com/4155937/68381650-7b8cea00-0152-11ea-90c3-ab1a03142f78.png)
5) Again, copy'n'paste is sometimes a little buggy, so adding the text using assign is more stable
( Click record, click notepad, write "test", Stop recording, the replace the value "test" with your variable, in my example thetext )
![image](https://user-images.githubusercontent.com/4155937/68381881-e3433500-0152-11ea-9641-1b5d8b229aee.png)

![GitHubIssue1](https://user-images.githubusercontent.com/4155937/68382334-c9eeb880-0153-11ea-9633-adbb2ca77734.gif)

**Comment by PhilipeTakeo** [comment]
It worked! Thanks
