### ISSUE TITLE
OpenRPA.Forms missing from Toolbox

### ISSUE THREAD

**Issue by haienlive** [open-rpa/openrpa#139]
Awesome tool! I downloaded the latest release and ran it through with the youtube video.
Forms seem to be missing from Toolbox list. Updating the package gives this error:
`NuGet.Packaging.Core.PackagingException: The package is missing the required nuspec file. Path: C:\Users\User\Downloads\OpenRPA\packages
   at NuGet.Packaging.PackageFolderReader.GetNuspecFile()
   at NuGet.Packaging.PackageReaderBase.GetNuspec()
   at NuGet.Packaging.PackageReaderBase.get_NuspecReader()
   at OpenRPA.Updater.OpenRPAPackageManager.InstallPackage(PackageIdentity identity)
NuGet.Packaging.Core.PackagingException: The package is missing the required nuspec file. Path: C:\Users\User\Downloads\OpenRPA\packages
   at NuGet.Packaging.PackageFolderReader.GetNuspecFile()
   at NuGet.Packaging.PackageReaderBase.GetNuspec()
   at NuGet.Packaging.PackageReaderBase.get_NuspecReader()
   at OpenRPA.Updater.OpenRPAPackageManager.InstallPackage(PackageIdentity identity)
NuGet.Packaging.Core.PackagingException: The package is missing the required nuspec file. Path: C:\Users\User\Downloads\OpenRPA\packages
   at NuGet.Packaging.PackageFolderReader.GetNuspecFile()
   at NuGet.Packaging.PackageReaderBase.GetNuspec()
   at NuGet.Packaging.PackageReaderBase.get_NuspecReader()
   at OpenRPA.Updater.OpenRPAPackageManager.InstallPackage(PackageIdentity identity)
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\openrpa.forms\1.0.10\openrpa.forms.1.0.10.nupkg
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\forge.forms\1.1.1\forge.forms.1.1.1.nupkg
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\mahapps.metro\1.6.5\mahapps.metro.1.6.5.nupkg
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\controlzex\3.0.2.4\controlzex.3.0.2.4.nupkg
  CACHE https://api.nuget.org/v3/registration4-gz-semver2/controlzex/index.json
  CACHE https://api.nuget.org/v3/registration4-gz-semver2/mahapps.metro/page/1.4.0-alpha037/2.0.0-alpha0170.json
  CACHE https://api.nuget.org/v3/registration4-gz-semver2/mahapps.metro/index.json
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\materialdesignthemes\2.5.0.1205\materialdesignthemes.2.5.0.1205.nupkg
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\materialdesigncolors\1.1.0\materialdesigncolors.1.1.0.nupkg
  CACHE https://api.nuget.org/v3/registration4-gz-semver2/materialdesigncolors/index.json
  CACHE https://api.nuget.org/v3/registration4-gz-semver2/materialdesignthemes/page/2.5.0-ci1137/2.5.1-ci1344.json
  CACHE https://api.nuget.org/v3/registration4-gz-semver2/materialdesignthemes/index.json
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\fastmember\1.4.1\fastmember.1.4.1.nupkg
  CACHE https://api.nuget.org/v3/registration4-gz-semver2/fastmember/index.json
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\humanizer.core\2.4.2\humanizer.core.2.4.2.nupkg
  CACHE https://api.nuget.org/v3/registration4-gz-semver2/humanizer.core/index.json
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\materialdesigncolors\1.1.3\materialdesigncolors.1.1.3.nupkg
  CACHE https://api.nuget.org/v3/registration4-gz-semver2/materialdesigncolors/index.json
  CACHE https://api.nuget.org/v3/registration4-gz-semver2/forge.forms/index.json
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\toastnotifications.messages\2.5.1\toastnotifications.messages.2.5.1.nupkg
  CACHE https://api.nuget.org/v3/registration4-gz-semver2/toastnotifications.messages/index.json
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\openrpa.interfaces\1.0.11\openrpa.interfaces.1.0.11.nupkg
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\openrpa.namedpipewrapper\1.0.10\openrpa.namedpipewrapper.1.0.10.nupkg
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\newtonsoft.json\12.0.2\newtonsoft.json.12.0.2.nupkg
  CACHE https://api.nuget.org/v3/registration4-gz-semver2/newtonsoft.json/index.json
  CACHE https://api.nuget.org/v3/registration4-gz-semver2/openrpa.namedpipewrapper/index.json
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\flaui.uia3\1.3.1\flaui.uia3.1.3.1.nupkg
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\flaui.core\1.3.0\flaui.core.1.3.0.nupkg
  CACHE https://api.nuget.org/v3/registration4-gz-semver2/flaui.core/index.json
  CACHE https://api.nuget.org/v3/registration4-gz-semver2/flaui.uia3/index.json
  CACHE https://api.nuget.org/v3/registration4-gz-semver2/openrpa.interfaces/index.json
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\toastnotifications\2.5.1\toastnotifications.2.5.1.nupkg
  CACHE https://api.nuget.org/v3/registration4-gz-semver2/toastnotifications/index.json
  CACHE https://api.nuget.org/v3/registration4-gz-semver2/openrpa.forms/index.json`

**Comment by skadefro** [comment]
Hmm, yes seems there is something wrong. If i delete both folders (openrpa/packages) and redownload it all works. 
I have a lot of bug fixes ready to be released, i will upload a new zip file later today or tomorrow

**Comment by haienlive** [comment]
Will wait for release.

**Comment by skadefro** [comment]
Thank you for letting me remotely see the robot on your system.
First we found that all dll's where blocked, you/we can fix that by running the unblock.ps1 script
there for all addons did not get loaded.
Once that was fixed, we found 4 bugs
1) links in menu not working
2) Need to check if office is installed before loading office addon
3) uninstall not working in package manager
4) python runtime file missing
All those should have been fixed now, could you try and see if things are working for you now ?

**Comment by haienlive** [comment]
I got around to testing the new build. A couple of things:
1.Running the unlock.ps1 file failed so I had to run the command manually
2.Still getting this error something
![Screen Shot 2019-11-14 at 3 05 26 PM](https://user-images.githubusercontent.com/55713870/68904281-726fc000-06f2-11ea-8cbe-f545fee92a4a.png)
3. Getting this error in the logger
`[13:00:45.692][Error] System.DllNotFoundException: Unable to load DLL 'python37': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at OpenRPA.Java.Plugin.Initialize(IOpenRPAClient client)
   at OpenRPA.Interfaces.Plugins.<LoadPlugins>d__6.MoveNext()`

4. Also these
`[13:00:45.332][Error] System.ApplicationException: Error loading the Java Access Bridge DLL.
This usually happens if the Java Access Bridge is not installed.
Please make sure to install the 64-bit version of the Java SE Runtime Environment version 7 or later. Alternatively, try running the 32-bit version of OpenRPA if a 32-bit version of the JRE is installed. ---> System.Exception: Error loading library "WindowsAccessBridge-64.dll" ---> System.IO.FileNotFoundException: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at WindowsAccessBridgeInterop.Win32.UnmanagedLibrary..ctor(String fileName)
   --- End of inner exception stack trace ---
   at WindowsAccessBridgeInterop.Win32.UnmanagedLibrary..ctor(String fileName)
   at WindowsAccessBridgeInterop.AccessBridge.LoadLibrary()
   --- End of inner exception stack trace ---
   at WindowsAccessBridgeInterop.AccessBridge.LoadLibrary()
   at WindowsAccessBridgeInterop.AccessBridge.Initialize()
   at OpenRPA.Java.Javahook.init()
[13:00:45.270][Debug] javahook.init()
[13:00:45.208][Information] Initialize plugin Java
[13:00:45.144][Information] Initialize plugin Image
[13:00:45.098][Information] Initialize plugin IE
[13:00:44.629][Error] loadPlugins
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at OpenRPA.Interfaces.Plugins.<>c__DisplayClass6_0.<LoadPlugins>b__0()
[13:00:44.519][Error] loadPlugins
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at OpenRPA.Interfaces.Plugins.<>c__DisplayClass6_0.<LoadPlugins>b__0()
`
5. Looks like it only works on window 10, not major but window 7 doesn't work at all.

**Comment by haienlive** [comment]
6. I don't want to use the macro but I want to manually open an application and do things. I created "Open Application" and launched something fine. I then drag "ClickElement". Here I have to manually input the element? I couldn't use the selector like when I "Open Application"?

**Comment by skadefro** [comment]
**the errors:** The idea is, that everything is plugin based, and you install/uninstall what you need, using the package manager.
You don't have office, you dont have python, you don't have java installed, so those addons was not really supposed to be there.
But other people complaint it was frustrating they had to download it all using the package manager and wanted me to bundle it, so that means you need to uninstall it instead. I feel a little I'm running around in circles here. 
It seems I need to start focusing on creating an installer instead of using zip files, that would also remove the need to unblock files

**6:** Not sure what you mean by macro ?
But the idea is, you get an element using "GetElement" from the addon that correspond with the technology used to find that element ( java, nm, ie, windows etc ) and then inside that you add an action, like click, highlight, get related element etc.

**Comment by skadefro** [comment]
I've left you a few replied on slack

**Comment by haienlive** [comment]
Thanks for all the help. Closing this one since its dated now.
