### ISSUE TITLE
Insert data from pdf to excel file.

### ISSUE THREAD

**Issue by PhilipeTakeo** [open-rpa/openrpa#153]
Hi Allan

I need help to build this workflow. There are some .PDF files at my documents folder, and there is an excel file. The Robot needs to get some information in a .PDF and to write them on excel file.
E.g:
document.PDF
There are "number", "full name", "ID" and so on ...
document.XLSX
Some of theses fields need to be copied from .PDF to Excel. 

Questions:
1) Wich is the best way to open .PDF file?
Because the action "OpenApplication" doesn't work to open PDF. After read the data, the PDF file should be deleted.

2) Get element to store data from PDF.
Will "get element" works to get the data form a PDF file?

3) How to "WriteCell" ?
I don't know how to write on next Cell, when the RPA will read a new document and write it, need to start on next empty cell.

4) How to loop a flow?
 This flow needs to be repeted until the .PDF file is over.

P.s: The origem of PDF file isn't a image, it is a text.

No hurry to answer this.

I will be very grateful for your help.

Thanks

**Comment by skadefro** [comment]
I need to create an read pdf activity. I will have time for that in a few days.
To have something to test on, could you share one of the pdf’s? You can upload it here or share it in a private message on slack

**Comment by PhilipeTakeo** [comment]
ok.

This is a type of invoice.



[nf04.pdf](https://github.com/open-rpa/openrpa/files/3893769/nf04.pdf)

**Comment by skadefro** [comment]
Sorry for the wait. I have now pushed a new version of the robot that has an ReadPDF activity. Using the result from AllText it should be fairly easy for you to do what you wanted. For more advanced pdf parsing, look at the [PdfReader](https://github.com/itext/itextsharp) object from Result. 
WriteCell uses the Cell property to know where to write, so fill that dynamically. A typically way is create a index variable of the type int and increase it doing each loop, and the in Cell write
`"A" & index.ToString()`
If you want to add to an existing excel fill, you want to know what is the next empty Row, then use ReadRange without setting the Range property, then read LastUsedRow for you index variable (+1)

**Comment by PhilipeTakeo** [comment]
Thanks Allan.

I'll try it.

**Comment by PhilipeTakeo** [comment]
In the footer of the OpenRPA Tool, what's the meaning of  "NM: online " sometime it stays offline.

![Screenshot_1](https://user-images.githubusercontent.com/56645803/70088273-b02a7f00-15f4-11ea-8018-dfd83887db34.jpg)

**Comment by skadefro** [comment]
It shows if the robot is connected to the chrome or firefox addon. If you install the Java addon it will also show how many VM’s it has detected.

**Comment by skadefro** [comment]
Can i close this issue?

**Comment by PhilipeTakeo** [comment]
Yes!

**Comment by skadefro** [comment]
Ok, feel free to ask here or on slack, if you have other questions, issues or suggestions.

**Comment by engahmed1190** [comment]
@skadefro , can you use [itext7-dotnet]https://github.com/itext/itext7-dotnet), it supports other languages rather than English.

**Comment by skadefro** [comment]
Please ask on rocket chat, I don’t want to turn this issue into a chat. ( I have follow up questions )
