### ISSUE TITLE
install guide

### ISSUE THREAD

**Issue by madsholme** [open-rpa/openrpa#155]
Hi

are there any installation documentation on how to set this up correctly? with backend and everything?

**Comment by skadefro** [comment]
When you say backend, do you mean high density robots, or openflow?
The high density robots is still en beta and is getting update a lot, i will try and create a guide once i bring it out of beta.
I have prioritized openrpa over openflow, since you can easy use my demo environment to test things out. But once i get around to it, what would be most important for you ? 
Running a non redundant system on Docker CE, or how to install and configure it, in DockerSwarm, Kubernetes or OpenShift ?

**Comment by madsholme** [comment]
Thanks for the answer. When i say backend, i mean everything that is required for running scheduled robots. I was hoping it would run on a windows platform, as in our environment we are looking for ways to automate different programmes. usually data extraction from one system to another(all more or less windows based).

our current solution works with a backend website where you can monitor how each robot runs, and schedule them. and then it works on a windows server, where it will execute the commands.

**Comment by skadefro** [comment]
The robot can only run on windows. It can run standalone, but to get the best utilisation and functionality you should connect it to an openflow instance. 
The scalability of the openflow platform is dependent on docker swarm/kubernetes/openshifts network load balancing and persistent storage functionality, but if you don't need high availability you can run it on a simple docker ce installation on both linux, mac or windows.
Openflow, per default, is run using linux docker container images, that runs on both linux, mac and windows. With a bit of work, you can also run it outside docker on both linux and windows ( i do that while developing and testing ) by installation mongodb and rabbitmq locally and then run either OpenFlow/index.ts or OpenFlowNodeRED/index.ts

**Comment by madsholme** [comment]
Thanks again for the answer. I guess that answers my question perfect. This looks very promising!

**Comment by skadefro** [comment]
So not an install guide, but maybe good enough ?
If you look in [openflow](https://github.com/open-rpa/openflow) i have added a docker-compose-traefik.yml
Using docker-compose or [portainer](https://www.portainer.io/) you can easily get up and running ( you need to modify the url's and update the mount point if your on windows )
Will that help ?

**Comment by madsholme** [comment]
Hi

it would be a step in the right direction. And would def be something i would look into. Thanks!

**Comment by skadefro** [comment]
Did you have a chance to test it? Do you need any help, or a demonstration?

**Comment by madsholme** [comment]
Sorry havent really had any time to loot into it yet, due to other more urgent matter going on. Im still keeping an eye out on it, and hope to try and set something up localy in feb.

**Comment by skadefro** [comment]
I don't have a portainer installation i can test against, i normally use "docker-compose up"
But i have soneone using it, he's docker file looks [like this](https://github.com/kddige/openflow/blob/master/docker-compose-traefik.yml) is that any help ?

**Comment by madsholme** [comment]
same error.. i think it has something to do with characters in the config file. i will try and have a look later.

**Comment by skadefro** [comment]
The dockerfile i linked is actually used on windows as well, so that should work, did you make sure docker is running in linux mode ?  ( i believe docker per default only supports windows images, when installed on windows per default )
https://github.com/docker/for-win/issues/1829#issuecomment-374560724

**Comment by madsholme** [comment]
thanks i got it running it :) i think it was my docker that was broken. A reinstall and it just works.

now stupid question time:
1: the rabbitmq interface works on http://localhost.openrpa.dk:15672/ (i changed my hostfile), and http://localhost.openrpa.dk:8080/dashboard/#/ shows træfik site. is that the site that will show the robots, and run them?

2:  if i launch openrpa.exe it asks me to sign in on demo1.openrpa.dk should this not be changed to the local site now? (the stuff running in docker) ? 

im interested in how to get a server to run scheduled rpa robots, and how i create a enviorement like that. I understand you may not be that far along with that part?

**Comment by skadefro** [comment]
Maybe we should schedule a google meet, and i can show you?
1) *.localhost.openrpa.dk is registered in public dns and should work without cyanging your host file, unless you want to access it from another host or have sone NAT/PAT networking setup.
So in your eksample http://localhost.openrpa.dk/ should be the webinterface where amongst other things you can monitor and run adhoc workflows on robots. 
And on http://localhost.openrpa.dk:1880 you have access to nodered where amongst other things you can schedule robots and have drag and drop access to 1000’s of different systems
2) go to “My Documents\openrpa” open settings.json and change wsurl to the api docker host. If not using https use ws:// instead of wss://

**Comment by madsholme** [comment]
A google meet would be interesting, im just really bussy and usaly only have time to look at this in the night atm. I hope my schedule clears up with in a few weeks.

http://localhost.openrpa.dk/ just gives me an custom 404 not found msg. http://localhost.openrpa.dk:1880/ gives me connection refused.

if i change the connection wsurl in the settings.json file to ws://localhost.openrpa.dk i get a disconnected from ws://localhost.openrpa.dk, unable to connect... Seems there is still something wrong with the docker setup. I will look at it a bit more and see how it goes, thanks for the help so far.

**Comment by skadefro** [comment]
i have time in the evenings if we can do it before 21

So the docker-compose.yml file is to make everything work on localhost using portsto keep things uniqe among the services. Web/api on port 80, nodered on 1880 and rabbitmq on 15672
docker-compose-traefik.yml is a solution to use domains as the uniqe entry, so in my example
localhost.openrpa.dk is the web/api
nodered1.localhost.openrpa.dk is the workflow engine
mq.localhost.openrpa.dk is the rabbitmq interface

So if your using trafik, you need to match the domain in your hostfile with the once in the yml file for instance    - "traefik.http.routers.web.rule=Host(`localhost.openrpa.dk`)"

**Comment by madsholme** [comment]
Just had a little baby, so scheduling is kinda hard atm, but its a good offer thanks.

just to be sure, i am only running the traefik.yml, i just used youre domain "localhost.openrpa.dk" to make it easy. 

and like i said localhost.openrpa.dk gives me 404 on port 80, port 15672 gives me rabbitMQ, 1880  gives me 404, and 8080 gives me the træfik dashboard.

is it my mountpoint for mongodb ? that is the problem?
this is how the traefik.yml looks atm:
http://pastebin.com/j2mSgUNX

**Comment by skadefro** [comment]
If you give me 2 minutes i can start my computer and we can proberly fix this fast?

**Comment by madsholme** [comment]
no problem, but if you got better things to do, it dosent have to be now :)

**Comment by skadefro** [comment]
https://meet.google.com/ycm-swbs-dee

**Comment by skadefro** [comment]
And for sharing screen https://get.teamviewer.com/openrpa

**Comment by skadefro** [comment]
We got things running and agreed to close this issue. Thank you for your time, let me know if you need more assistance.
