### ISSUE TITLE
Can I use Open-rpa without program experience 

### ISSUE THREAD

**Issue by sunbegin123** [open-rpa/openrpa#172]
Hi
Allen:
I learn now and I can only use the record function now.
I'm not a programmer, can I use the Open-rpa to make a workflow? such as your example "Excel and browser interaction, used for vat number lookup", I'm not sure if I need programming during the build process
On the other hand, which language is used for Open-rpa programming? python? Java?

**Comment by skadefro** [comment]
Using workflows is to help non-developer have easier access to logical operations, it is still coding :-)
In some cases you will not be able to avoid coding, but you can come far with just the workflow designer.
The default language inside the robot is VB.NET but using InvokeCode you can also write PowerShell, C# or Python code.
If you are also using OpenFlow, again you can do most of the work using the workflow designer, and the default language is JavaScript, but you can install modules and code i Perl, Python and many other languages.

**Comment by sunbegin123** [comment]
OK， Thank you very much.
