### ISSUE TITLE
ClickElement

### ISSUE THREAD

**Issue by PhilipeTakeo** [open-rpa/openrpa#178]
Hey there.

I was testing another open source RPA tool, and just noticed a cool action. It is about click, this action can click anywhere on screen, not only when an APP is opened and click on position inside the APP.

Is possible to do this with OpenRPA? (click anywhere on my screen, with or without a program opened)

Would be cool an action to locate mouse position, for example if I do a random click on my screen, it returns the position X and Y. Sometime to get the accurately mouse position helps a lot.

**Comment by skadefro** [comment]
I don't understand how that specifically should work ?
Do you want to click at a specific X,Y coordinate ? If so, how is that useful if the app is closed ?
Or do you mean, if you can click on an element even when the app is minimized ? In that case you can already do that, by using VirtualClick set to true

**Comment by PhilipeTakeo** [comment]
I don't understand how that specifically should work ?
Doing a random click. Independently the app is closed or not, we can do random clicks on screen.

Do you want to click at a specific X,Y coordinate ?
Yes.

 If so, how is that useful if the app is closed ?
It is useful when we can't easily find an element, xPath or the exact X,Y coordinate in the web browser or app.
E.g: We don't need to set an item to ClickElement,  only to set a X,Y coordinate and do a click.

**Comment by skadefro** [comment]
Click record, Click your desktop, top recording
And you can dynamically set X and Y offset on ClickElement, will that solve your problem ?

**Comment by PhilipeTakeo** [comment]
I'll try

**Comment by skadefro** [comment]
Any luck with that ? 
If not, can you give an example where this would be useful, maybe i could create a specific activity (or improve an existing ) if i better understood what it is, your trying to achieve

**Comment by PhilipeTakeo** [comment]
I didn't do yet.
I'm working on another tasks, but i'll try to record and explain about this activity.

Thanks

**Comment by skadefro** [comment]
What is the status of this ?

**Comment by PhilipeTakeo** [comment]
It's Ok.

I'm using recording to click at a specific position. You can close!

**Comment by skadefro** [comment]
Ok, let me know if you later need something more specific, with an example.
