### ISSUE TITLE
When playing, the button will be repeatedly clicked

### ISSUE THREAD

**Issue by zengande** [open-rpa/openrpa#183]
My workflow is like this
![image](https://user-images.githubusercontent.com/37611092/71407880-43e0ef80-2677-11ea-932f-dc4ab6498fc9.png)

But I got the result like this
![image](https://user-images.githubusercontent.com/37611092/71407916-6246eb00-2677-11ea-9148-2ba16ef9fb5c.png)

This is the latest version, the old version does not have this problem.

**Comment by skadefro** [comment]
Year right, how did i miss that, Looking into this right away

**Comment by skadefro** [comment]
Thank you for letting me know. For some weird reason, this did not show up in all applications, so the bug has been there for a few days. I've uploaded a new version of 1.0.63 with this fixed.
Please check if this also solves the problem in your end too ?

**Comment by skadefro** [comment]
I've bumped the version to 1.0.64 and added a few more fixes and improvements ...

**Comment by zengande** [comment]
Yes, this bug has been fixed, thank you!
