### ISSUE TITLE
Project example

### ISSUE THREAD

**Issue by PhilipeTakeo** [open-rpa/openrpa#191]
Hi!

I would like to know how you built these two RPA.

1-Excel and browser interaction, used for vat number lookup
2-Automate creating contacts in CRM app from excel list

Can you send them?

**Comment by dude613** [comment]
Also interested :)

**Comment by skadefro** [comment]
Please update to at least version 1.0.70
2) Automate creating contacts in CRM app from excel list ( and json )
Then download [mycrm-ReadAndFill](https://github.com/open-rpa/examples-files/raw/master/mycrm/mycrm-ReadAndFill.xaml)

**Comment by skadefro** [comment]
And for number 1, Excel and browser interaction, used for vat number lookup
Please update to at least version [1.0.70](https://github.com/open-rpa/openrpa/releases)
Then download and import [vatnumber-lookup](https://github.com/open-rpa/examples-files/raw/master/vatnumber-lookup/vatnumber-lookup.xaml)

Will these 2 examples do ?

**Comment by PhilipeTakeo** [comment]
yep sure, thanks...

I'll study them.

**Comment by PhilipeTakeo** [comment]
Is there a task manager for OpenRPA?

e.g: To schedule 10 robots to run at different time or day, to check if robot ran or it is running as scheduled, and so on...

**Comment by skadefro** [comment]
I believe i answered that already in #154 
Can i close this issue, was the examples good enough ?

**Comment by PhilipeTakeo** [comment]
Yes, thanks.
