### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by weizier** [open-rpa/openrpa#199]
![image](https://user-images.githubusercontent.com/8486415/72069304-da710a00-3321-11ea-88ef-cc10d10ba2d0.png)

MSB3073	命令“nuget.exe push bin\ReleaseNuget\net4\..\OpenRPA.WindowsAccessBridgeInterop.1.1.6.nupkg -Source nuget.org”已退出，代码为 9009。	WindowsAccessBridgeInterop	D:\RPA\openrpa\WindowsAccessBridgeInterop\WindowsAccessBridgeInterop.csproj	24

**Comment by skadefro** [comment]
It looks like you are trying to run the releasenuget configuration, than will not work without nuget credentials setup beforehand.
Either change the configuration to debug or release
![image](https://user-images.githubusercontent.com/4155937/72069579-cb6d6600-32e7-11ea-9a7a-71f047e4837f.png)

or remark out(or delete), the nuget task inside all projects files.
![image](https://user-images.githubusercontent.com/4155937/72069640-e7710780-32e7-11ea-9933-148bc0701d8e.png)

**Comment by skadefro** [comment]
Did this solve you problem, or does this need more investigation?

**Comment by skadefro** [comment]
I am assuming you had the problem solved, if not feel free to re-open this issue.
