### ISSUE TITLE
SubMenu

### ISSUE THREAD

**Issue by PhilipeTakeo** [open-rpa/openrpa#200]
Hi Allan.
I need some help, to click on a submenu.

This website for example, https://acme-test.uipath.com/account/login you can log in with teste1@teste.com, password teste1.

![Screenshot_1](https://user-images.githubusercontent.com/56645803/72177488-89afee80-33bf-11ea-81b0-57f8c42fb136.jpg)

In this case, i can click on "User Options" and click on "reset test data." On this site, when I click on the first menu, the submenu remains fixed and then I can perform another action and click again.

I need to do the same click on another site, but the submenus is only displayed when the mouse is over the first menu, if i move the mouse out the submenu disappears.

I don't know if i could explain, but that's it.

**Comment by skadefro** [comment]
Interesting dilemma ... So i have seen a few applications and websites, when you click the menu it closes, so you can only open it when doing a mouse over, extremely bad design, if you ask me.

So the easy solution is to just move the mouse to the menu point using InvokeCode
`FlaUI.Core.Input.Mouse.MoveTo(new System.Drawing.Point(item.Rectangle.X + 20, item.Rectangle.Y + 5));`

Nah, just kidding, not many would figure that out, so I have added a new MoveMouse activity in version 1.0.77. 
It takes an element just like ElementClick, and you can set AnimateMouse to true. 
This will move the mouse to the offset of the element, and hopefully open your menu, without doing a mouse click.
![image](https://user-images.githubusercontent.com/4155937/72202675-90dc0880-3462-11ea-9848-f3045b64e426.png)

**Comment by arpeeay** [comment]
Absolute stunning reaction time!

**Comment by PhilipeTakeo** [comment]
It worked!!!
Thanks

**Comment by skadefro** [comment]
I’m glad I could help. 😊
