### ISSUE TITLE
ReadRange failure

### ISSUE THREAD

**Issue by PhilipeTakeo** [open-rpa/openrpa#204]
Hey Allan, i'm sorry to open issues a lots, but i'm doing a thorough study of your tool.

I still have problems working with excel. To open an excel file i need to type the arguments manually, because the selector can't find the file path, but with word.docx it works perfectly.

Another problem is workflow that read an excel file and writes the data into a program "to simulate an ERP and Excel business process". Workflow stops running on ReadRange, can you take a look ?

[Lancamentos.zip](https://github.com/open-rpa/openrpa/files/4066442/Lancamentos.zip)

I tried to run your example (mycrm-ReadAndFill), it also stops to run at ReadRange.

![Running mycrm-ReadAndFill](https://user-images.githubusercontent.com/56645803/72458374-3961d380-37a7-11ea-9834-267036e93f72.jpg)

**Comment by skadefro** [comment]
Do you have excel 2019 installled?

**Comment by PhilipeTakeo** [comment]
2013
![Screenshot_1](https://user-images.githubusercontent.com/56645803/72459271-2f40d480-37a9-11ea-9751-e8173f1295b8.jpg)

i mean, when i use OpenApplication to open an excel or word doc. 
docx works but excel not.

**Comment by skadefro** [comment]
Can you show me that, using teamviewer?
https://get.teamviewer.com/openrpa

**Comment by PhilipeTakeo** [comment]
yes

**Comment by skadefro** [comment]
Then click the link, and run it?

**Comment by skadefro** [comment]
Remove the teamviewer dialog.
Found a solution to the problem.
