### ISSUE TITLE
Binaries not signed with strong name key

### ISSUE THREAD

**Issue by vigew** [open-rpa/openrpa#208]
When getting the module via NuGet manager in Visual Studio, the DLL is not signed with a strong name key. Trying to load the DLL from another module that is signed fails with the error "A strongly-named assembly is required".

**Comment by skadefro** [comment]
What package are you trying to use ? Are you trying to create an addon ?
( then I may need to update the packages, haven't done that in a while )
I just tested by creating a blank project and installing openrpa.interfaces, and I did not get any errors ?
![image](https://user-images.githubusercontent.com/4155937/72802025-1de54580-3c4b-11ea-90aa-bde90882d437.png)
The robot ignores signing, so that is not needed to create new activities/detectors/recorders/runplugins

**Comment by vigew** [comment]
I was trying to use OpenRPA.Elis.Rossum
I need to call it from a plug-in of some application. The plug-in needs to be signed with a strong name key. When running the application, the above mentioned error is thrown as soon as something from the OpenRPA.Elis.Rossum module is used.

**Comment by skadefro** [comment]
So you want to use it, from something other that OpenRPA ?
tbh, i made the addon only for that use, but should work with anything targeting microsoft workflow foundation, Does that application also have a rehosted Workflow Designer embedded ?

**Comment by vigew** [comment]
No, I wasn't even aware of that. I was looking for something that makes it easier to use the elis.rossum.ai web service. The Description of the module in the NuGet packager manager suggested that this is the purpose of the module.
I guess that means it is not what I am looking for to begin with but maybe you can improve the description to make this clear to people who don't know OpenRPA.
Thank you for the quick answers.

**Comment by skadefro** [comment]
Makes sense, i will add a notice in the description about that.

But have a [look at the code](https://github.com/open-rpa/openrpa/tree/master/OpenRPA.Elis.Rossum), you will see the API is very straight forward to work with, you honestly don't need a package for that :-)
You get an API key by submitting username/password, then get a queue, and then either 
"get a file" and parse the export, 
or upload a file, monitor the status and wait for the file to come in the exported state.
then parse the export
