### ISSUE TITLE
openrpa : unable to register

### ISSUE THREAD

**Issue by doubleachmad8080** [open-rpa/openrpa#209]
hi allan, i just installed openrpa released on 4 days ago, installation success but didn't find any way to register. could u help me

**Comment by doubleachmad8080** [comment]
AADSTS90019: No tenant-identifying information found in either the request or implied by any provided credentials.

**Comment by skadefro** [comment]
I know it can be a little confusing. 
Office 365 is not the same as Windows Live ID / a private Microsoft Account. ( i will see if i can make support for that )
I recommend you try using a google id, and if you don't have one, you can also just type a new username and password in the signin page, and it will automatically create a new user, with those credentials.

**Comment by doubleachmad8080** [comment]
thanks sir, already success to login to demo server. thanks sir

**Comment by skadefro** [comment]
sounds good
