### ISSUE TITLE
Variables and Arguments?

### ISSUE THREAD

**Issue by PhilipeTakeo** [open-rpa/openrpa#211]
Hi.

What's the difference between Variables and Arguments?
Can you give an example?

How can i change the language?

**Comment by skadefro** [comment]
Variables are bound to and only accessible from within a scope (often a sequence and everything inside it)
Arguments are set/read from what ever executes the workflow (like openflow or another robot) and is accessible throughout the whole workflow.
You cannot change the language, i have not made support for c# expression in the designer.
But you can still code i C# and other languages, using InvokeCode activity

**Comment by PhilipeTakeo** [comment]
I mean the language of the tool.
(german, portuguese, english)

**Comment by skadefro** [comment]
Close the robot
Open settings.json in "My Documents\OpenRPA" and set a value to "culture"
Use the LCID string from https://www.science.co.il/language/Locale-codes.php so for english you can use en-us for german de-de and so on.
You **NEED** to delete layout.config after changing language
If culture is empty, it will use whatever display language you have in windows.

**Comment by PhilipeTakeo** [comment]
Thanks :)
