### ISSUE TITLE
Google Login is not working

### ISSUE THREAD

**Issue by FANMixco** [open-rpa/openrpa#213]
Personally, I'm not sure why this is mandatory to use the core of the App, but I'm getting this issue:

![image](https://user-images.githubusercontent.com/1666156/73522172-0571e980-4408-11ea-8ba3-eeb9613c714c.png)

The application is considered insecure by Windows too since I got an additional notification when I tried installing it the first time.

**Comment by skadefro** [comment]
Yes, I had someone else mention this, we couldn't really figure out what it was, since most google answers say you need to allow unsecure logins, and that did not work for him.
I've been looking a little on this again now, and it seems this can be solved my changing the user agent string, I will create a new build, that has this feature. I will update this issue when it's up.

**Comment by skadefro** [comment]
I've spent some time trying to reproduce this, to no avail. Apparently you need to disable "less secure apps" to get this error, and be coming from a non-supported browser. I don't have "less secure apps" enabled, and i tried creating a new gmail account, and still don't get the error, but I've seen while helping someone else, so i acknowledge is does happen. So my reasoning is changing the user agent to a supported browser should fix this, i just have no way of testing if this solves it.
Could you please test if [this release](https://github.com/open-rpa/openrpa/releases/tag/1.0.79-beta2) fixes the issue for you ?
And regarding being mandatory. It is not, You can run the robot fine without connecting to an [openflow](https://github.com/open-rpa/openflow) instance, by removing the wsurl value, as explained in your another issue #214
So why does it prompt to login to [demo1.openrpa.dk](https://demo1.openrpa.dk/) per default ? To show people what they can get if they both install the robot and [openflow](https://github.com/open-rpa/openflow), but many don't have the option or skills to install and configure [openflow](https://github.com/open-rpa/openflow) locally, so I'm offering a free demo setup to test it in.

**Comment by FANMixco** [comment]
> I've spent some time trying to reproduce this, to no avail. Apparently you need to disable "less secure apps" to get this error, and be coming from a non-supported browser. I don't have "less secure apps" enabled, and i tried creating a new gmail account, and still don't get the error, but I have seen this while helping someone else, so i acknowledge is does happen. So my reasoning is changing the user agent to a supported browser should fix this, i just have no way of testing if this solves it.
> Could you please test if [this release](https://github.com/open-rpa/openrpa/releases/tag/1.0.79-beta2) fixes the issue for you ?
> And regarding being mandatory. It is not, You can run the robot fine without connecting to an [openflow](https://github.com/open-rpa/openflow) instance, by removing the wsurl value, as explained in your another issue #214
> So why does it prompt to login to [demo1.openrpa.dk](https://demo1.openrpa.dk/) per default ? To show people what they can get if they both install the robot and [openflow](https://github.com/open-rpa/openflow), but many don't have the option or skills to install and configure [openflow](https://github.com/open-rpa/openflow) locally, so I'm offering a free demo setup to test it in.

I'll let you know on Monday :).

**Comment by skadefro** [comment]
Did you have time to test this ?

**Comment by skadefro** [comment]
I'm assuming this now works or you don't have time to test.
Feel free to write if you want me to reopen this
