### ISSUE TITLE
Cannot create new workflow or project

### ISSUE THREAD

**Issue by FANMixco** [open-rpa/openrpa#214]
After I was able to login with my local credentials, I have blocked the options for creating new workflows or projects:

![image](https://user-images.githubusercontent.com/1666156/73524247-06f1e080-440d-11ea-8c05-be06897d1c1c.png)

Any idea, what should I do?

**Comment by skadefro** [comment]
You left out the most important part in this screenshot, the status bar at the bottom.
My guess is, the robot is trying to connect to something and failed, if you want to run the robot without being connected to an openflow instance, you need to remove the value in wsurl in settings.json you find in "My Documents\openrpa"
See [more here](https://github.com/open-rpa/openrpa/issues/55#issuecomment-502167179) 
Remember to close the robot before changing the file, or the robot will overwrite the chances when its closed down.
Does this solve your issue ?

**Comment by jonathan-barbero** [comment]
I had the same problem, removing the url worked.
Thanks.

**Comment by skadefro** [comment]
I'm assuming this is no longer an issue, feel free to write if you want me to reopen this.
