### ISSUE TITLE
OpenRPA.NM.Plugin.OnMessage contains suspicious if-statement

### ISSUE THREAD

**Issue by Dmitry-Me** [open-rpa/openrpa#215]
Here https://github.com/open-rpa/openrpa/blob/master/OpenRPA.NM/Plugin.cs

    private void OnMessage(NativeMessagingMessage message)

contains this if-statement

    if (!string.IsNullOrEmpty(message.data))
    {
       LastElement = new NMElement(message);
    }
    else
    {
       LastElement = new NMElement(message);
    }

with if-branch being identical to else-branch. This makes no sense. This code looks suspicious. Either one of branches should be changed or this code should be rewritted without if-statement.

**Comment by skadefro** [comment]
Agree, that makes no sense. 
I used to discard message with no data, but I've since added functions that can return without a result.
