### ISSUE TITLE
NewMailItem

### ISSUE THREAD

**Issue by PhilipeTakeo** [open-rpa/openrpa#217]
Hi.

I'm creating a workflow for sending emails to several addresses listed in a excel file. Everything working fine.

But I have a layout for the body of the email, the message has formatted letters and some images. How can I place this message into my email using NewMailItem?

How use "HTMLbody"?

**Comment by PhilipeTakeo** [comment]
And how to send for Cc - The secondary recipients of the email message

**Comment by skadefro** [comment]
You just add html as a string to the HTMLbody.
Like this 
[html-email.zip](https://github.com/open-rpa/openrpa/files/4158536/html-email.zip)

**Comment by PhilipeTakeo** [comment]
Thanks for your example.

**Comment by skadefro** [comment]
I have uploaded a new version, where NewMail item also have a CC and BCC property.
