### ISSUE TITLE
Does it support the  electron client or cef client

### ISSUE THREAD

**Issue by fjwgrace** [open-rpa/openrpa#218]
Now,some Clients are writtern by electron or cef which may be different with the chrome, so can we use openrpa to do the rpa work  for those electron Application?

**Comment by skadefro** [comment]
Yes and no, but not in a user friendly way.
The integration is based on the openrpa addon being loaded, so to get a good experience you would need to get that loaded as well. That is going to be nearly impossible in cef, but electron should be more "doable" ... a quick google search brought me to [this page](https://www.electronjs.org/docs/tutorial/devtools-extension), but i don't have something to test this on. Do you have a electron i could test this with ?

**Comment by fjwgrace** [comment]
> Yes and no, but not in a user friendly way.
> The integration is based on the openrpa addon being loaded, so to get a good experience you would need to get that loaded as well. That is going to be nearly impossible in cef, but electron should be more "doable" ... a quick google search brought me to [this page](https://www.electronjs.org/docs/tutorial/devtools-extension), but i don't have something to test this on. Do you have a electron i could test this with ?

you can download the electron demos  from this website：https://github.com/electron/electron-api-demos

**Comment by skadefro** [comment]
How sad, that would have been a good use case, but turns out that is [not supported](https://github.com/electron/electron/issues/7681#issuecomment-255670474) by electron.
