### ISSUE TITLE
Working with text

### ISSUE THREAD

**Issue by PhilipeTakeo** [open-rpa/openrpa#219]
I have this text in docx
"Lorem ipsum **{variable1}** dolor sit amet, consectetur adipiscing elit, sed do **{variable2}** eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad **{variable3}** minim veniam, quis nostrud..."

And I have these variables:
variable1 = "Spider Man"
variable2 = "Iron Man"
variable3 = "Captain America"

I will get the variable values from a form, then open the docx file above and replace the values.

Question, how do i replace them?

Why do i need this?
To draw up some contracts.

**Comment by skadefro** [comment]
I don't have any word activities yet, but i guess this is a good time to create a few.
I'm very busy on some projects right now, so i don't think i will have time to do this until the weekend or next week, i hope that is ok.

**Comment by PhilipeTakeo** [comment]
But even if there is a word activity, would another activity be necessary to replace these strings?

Anyway, I look forward for this activity.  :)

**Comment by skadefro** [comment]
Update to [1.0.79](https://github.com/open-rpa/openrpa/releases/tag/1.0.79) and test this. Will that do ?
[AddMarvelCharacter.zip](https://github.com/open-rpa/openrpa/files/4174156/AddMarvelCharacter.zip)

**Comment by PhilipeTakeo** [comment]
Yes! ;)
