### ISSUE TITLE
Is it possible to start an Automation from the console

### ISSUE THREAD

**Issue by LeonRuesterGitHub** [open-rpa/openrpa#224]
I am looking for a way to run an existing workflow form the console.
I could not find anything on this topic yet, it would be nice if you have access to the console params in the workflow too. Is this possible or maybe planed?

**Comment by skadefro** [comment]
That is not possible right, but should be easy to implement. I will see if i can find time for this tomorrow.

**Comment by skadefro** [comment]
openrpa.exe now accepts a number of key value pairs for running workflows from command line.
you can use - or / for defining the key, but it is optional
workflowid can either be the id for the workflow or the relative path ( project \ filename )
for instance
```
OpenRPA.exe /WorkflowID 5e451402478059b6448ec23f
OpenRPA.exe /workflowid project1\add_to_notepad.xaml
```
if the workflow takes arguments you can also send those from command line, for instance add_to_notepad takes a parameter with the name text, that it adds to notepad
`OpenRPA.exe /workflowid "dev\add_to_notepad.xaml" -text "Hi mom"`

Is this acceptable ?

**Comment by LeonRuesterGitHub** [comment]
This is perfect!
Thank you for your quick response and work, greatly appreciate it.
:)

**Comment by LeonRuesterGitHub** [comment]
Hello @skadefro ,
i just tried to follow your explanation, with a fresh installation of Open RPA and i am facing some difficulty. It might just be me not understanding how to use the features properly tho. I create an workflow, export it and try to pass it the argument via the console. But instead of executing the workflow it starts the application and nothing happens after that. Can you explain to me what i am doing wrong, really appreciate it.

Hear is what i tried:
![openRpa](https://user-images.githubusercontent.com/53171409/74662713-b7483e80-519a-11ea-9d4a-f68272dec53a.gif)

**Comment by skadefro** [comment]
Yes, the robot will only work with workflow "it knows" ( workflows that you can see in "open" tab ).
So when i wrote relative path ( project \ filename ), I'm referring to inside the robot.
I have uploaded a [new version](https://github.com/open-rpa/openrpa/releases/download/1.0.80-beta6/OpenRPA.exe) of the robot with a right click menu, so you can easily copy the id or name to use as parameter for the executable.
![image](https://user-images.githubusercontent.com/4155937/74664817-c0d3a580-519e-11ea-93fc-346bf8615dfe.png)

**Comment by LeonRuesterGitHub** [comment]
Okay thank you, now the workflow execute as expected.
Problem is i still cannot pass arguments to it + whenever i set a standard value for an argument it doesn't save probably.
could you please explain why that happens?

![openRpa2](https://user-images.githubusercontent.com/53171409/74716003-00959e00-522e-11ea-8ecf-361216ecd026.gif)

**Comment by skadefro** [comment]
part 1, arguments are case sensitive, it always try and keep everything in lower case to avoid issues.
part 2. I'm not sure i can fix this, Í've looked at it before but had no luck, i will have a look again to see if i find a solution on default's on arguments

**Comment by skadefro** [comment]
Oh, i found the bug ... workflow name give the XAML a class name that contains a space, that makes setting arguments illegal. I will write some code to ensure the class name of the workflow xaml does not contain space.
This will take a while since I'm completely booked the next 3 days, sorry for the delay

**Comment by LeonRuesterGitHub** [comment]
Alright it now works with the workaround thanks again for the help on this.

**Comment by skadefro** [comment]
I might need to give this some more work later, but for now this eliminates the spaces from class name. You can download the new [version here](https://github.com/open-rpa/openrpa/releases/download/1.0.80-beta7/OpenRPA.exe)
