### ISSUE TITLE
Install OpenRPA and OpenFlow 

### ISSUE THREAD

**Issue by yannickbleyCGI** [open-rpa/openrpa#232]
Hello, i'm usually working with RPA and i would like to test your solution OpenRPA. 
I want to install OpenRPA but every time i try to launch it, the windows of the application opens and closes 10 seconds later. I'm on windows 10.  
Also i didn't really understand the role of OpenFlow.

**Comment by skadefro** [comment]
That sounds like an addon generating an exception.
I've mostly seen that when people have pythin installed in a version that does "play well" with my OpenRPA.Script addon.
Could you try and rename C:\Program Files\OpenRPA\OpenRPA.Script.dll to OpenRPA.Script.dll.old or something, and see if that fixes the issue ?

**Comment by yannickbleyCGI** [comment]
It fixed the issue. 
Thank you. Excuse me if i bother you but i would like some indications on OpenFlow. I'm quite beginner on RPA. What's the purpose of OpenFlow with your solution ?

**Comment by skadefro** [comment]
no bother, it’s a very good question. Most RPA solutions have some kind of orchestrator, and for OpenRPA that is OpenFlow. OpenFlow is a server-based application that lets you orchestrate your Robots, but it also a workflow Engine that can integrate with more than 2000 different it systems, it also functions as a very scalable and secure database for it self and the robots.

**Comment by skadefro** [comment]
Sorry missed you main question on how to install OpenFlow 
That is a very broad question as it will differ depending on weather your installing on docker ce, dockerswarm, OpenShift or Kubernetes. But for easy demonstration you can installer docker ce in linux mode on windows/mac/linux and use one of the two docker-compose files to make a singler server installation running at https://localhost.openrpa.dk

**Comment by yannickbleyCGI** [comment]
Well, thank you for replying.  Everything you said is clear, i'm going to install it as you told me and i'll test it. 
I might come back to you for other questions.

**Comment by skadefro** [comment]
I’m assuming the main issue was solved, feel free to open another issue or contact me on slack if you have more questions or issues.
