### ISSUE TITLE
FileNotFoundException in OpenApplication

### ISSUE THREAD

**Issue by anjucheran** [open-rpa/openrpa#233]
When I am trying to use `OpenApplication` it always throwing an exception when I am selecting the element. I have followed your recent interview and just tried to redo the calculator addition.

![OpenApplication Issue](https://user-images.githubusercontent.com/23340269/75137790-8d4cca00-570e-11ea-8bed-6fc54a50b198.PNG)
Please guide me on this. Thanks!

**Comment by skadefro** [comment]
You need to remove the office addin.
Just close the robot, delete and the start the robot again
`C:\Program Files\OpenRPA\OpenRPA.Office.dll`

**Comment by anjucheran** [comment]
Thanks! It has worked.
