### ISSUE TITLE
What happens if the URL: "wss://demo1.openrpa.dk/ goes down?

### ISSUE THREAD

**Issue by RiddhiParekh1010** [open-rpa/openrpa#236]
I have a requirement from the client to automate one process which runs for a couple of years and I would like to go with the OpenRPA tool.
So the OpenRPA tool always be up and running for a couple of years?
I am asking this because, as I noticed OpenRPA depends on the URL: "wss://demo1.openrpa.dk/" to load the workflows and I have few questions in mind. So what happens if URL: "wss://demo1.openrpa.dk/" goes down? Automation process would function as it is or it will be stopped?
If it's going to stop, what is the preferred solution for this problem?

**Comment by skadefro** [comment]
Excellent question. There is a couple of answers to this.
OpenRPA is *not* dependent on demo1.openrpa.dk . OpenRPA can run in offline mode, where it saves everything locally. That means all OpenFlow features will not work. To get the full power and experience you will need to setup the client to talk with an OpenFlow instance. You can run this on-premise or any cloud provider. To make it easy for people to test and experience everything, the client per default connects to my demo environment. As the name implies, this is for demonstration purpose and there is no guarantees on this instance. (you can also support me, by buying an instance with support and SLA of me)
And lastly, what happens to the robot if your OpenFlow instance stops working. If the robot is already running, then nothing happens. Everything locally will keep working, but all OpenFlow features will fail. As soon as OpenFlow comes backup, the client will automatically reconnect and sync up any changes it may have. If you want to start a new robot, it will keep trying to connect but you cannot use it until it has “seen” OpenFlow. (if your OpenFlow is completely down and will never come up, you can remove the url from the settings file and it will load what is locally cached and function in offline mode )

**Comment by skadefro** [comment]
Did this answer your question ? Do you need more clarification ?

**Comment by RiddhiParekh1010** [comment]
Yes, I am also thinking of an alternate solution.
Is that possible to set up the Application on my localhost? If it's yes or possible, then what are the prerequisites and what would be the configuration setting to make an application up, on the localhost?

**Comment by skadefro** [comment]
So, if the solution is pure RPA, and if you don't want use demo1.openrpa.dk, all you have to do is remove the url from wsurl, and use the robot in offline mode.
If you want to use [OpenFlow](https://github.com/open-rpa/openflow) and do not trust demo1.openrpa.dk, then you can install it locally, either by setting everything up manually, or you can use one of the [docker-compose](https://github.com/open-rpa/openflow/blob/master/docker-compose-traefik.yml) files to have docker setup an complete environment for you. Works on windows, mac and linux

**Comment by RiddhiParekh1010** [comment]
@skadefro, Thanks for the detailed reply. It's really helpful.
