### ISSUE TITLE
Application Integration. SOAP Web Service and XML

### ISSUE THREAD

**Issue by PhilipeTakeo** [open-rpa/openrpa#238]
Can we Read data from SOAP XML with OpenRPA?

**Comment by skadefro** [comment]
If we skip talking about InvokeCode, the easy way of doing that would be to use OpenFlow
Just install https://flows.nodered.org/node/node-red-contrib-soap this using the palette, and then this can map the descriptor and allow you to call most SOAP services out there.
You can use Workflow In and Workflow Out nodes to expose an endpoint from NodeRed to the robot and send the result back.

**Comment by skadefro** [comment]
Did you test it ? Did it work, or do you need help ?
I've also made a little [example](https://raw.githubusercontent.com/open-rpa/examples-files/master/powershell-vatnumber-lookup/VATCheck.xaml) using InvokeCode and powershell if that was more what you where looking for.

**Comment by PhilipeTakeo** [comment]
I didn't try yet.
I'm still a little confused about this, i need to have some knowledge about API and then i will try to apply your solution.
thanks for now, you can close this issue.

**Comment by skadefro** [comment]
No problem. Drop me a message here, on slack or skype if you need help :-)
