### ISSUE TITLE
Error when trying to invoke code

### ISSUE THREAD

**Issue by caiohsfar** [open-rpa/openrpa#242]
Im getting an error when trying to drop the activity "invoke code".
Some idea of what's happening?

![error-rpa](https://user-images.githubusercontent.com/34478592/75904999-f0cbab80-5e22-11ea-827b-bf8d7ba44685.png)

**Comment by skadefro** [comment]
That error is super weird. 
Are you using the latest version of openrpa? 
Did you use the installer or package manager to update ? If package manager, can you try using installer to make sure you have all the latest versions of the plugins.

**Comment by caiohsfar** [comment]
Yes, i am using the latest version and the installer

**Comment by caiohsfar** [comment]
Yes, i installed the update with this link but the problem persists
I recorded my screen:
https://drive.google.com/file/d/1snihJYfUuT18WLopsCJqQMo7w1quem3m/view

**Comment by skadefro** [comment]
That is ekstremly weird, do you get that error with any other activity, from the same or other dll’s/extensions ?
Is there a chance, i could get remote access and test some things? I booked all day tomorrow but have time again Saturday and onward

**Comment by skadefro** [comment]
So should we setup a session where you can show me this, or did this issue resolve itself somehow ?

**Comment by skadefro** [comment]
I can not reproduce this and I can not get access to see it. Closing, but feel free to write here again, if you want to look at this at again.
