### ISSUE TITLE
Rossum Elis openRPA error in UPLOAD file section.

### ISSUE THREAD

**Issue by abneetwats24** [open-rpa/openrpa#253]
I got this when I start my workflow for openRPA.Rossum.Elis
in Upload File section.

[15:26:51.882][Output] New Workflow failed in 00:01.589
# System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Net.WebRequest.Create(String requestUriString)
   at OpenRPA.Elis.Rossum.SimpleRequests.HttpUploadFile(String url, String file, String akey, String paramName, String contentType, NameValueCollection nvc)
   at OpenRPA.Elis.Rossum.UploadFile.Execute(CodeActivityContext context)
   at System.Activities.CodeActivity.InternalExecute(ActivityInstance instance, ActivityExecutor executor, BookmarkManager bookmarkManager)
   at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation)

**Comment by skadefro** [comment]
What value do you have in Queue ?

**Comment by abneetwats24** [comment]
String

**Comment by skadefro** [comment]
Queue must be an URL.
Use GetQueues to get a list of queue objects, then use the url property in the Queue property
![image](https://user-images.githubusercontent.com/4155937/77635221-8950d980-6f52-11ea-991c-a8ea6aaf917b.png)
![image](https://user-images.githubusercontent.com/4155937/77635255-94a40500-6f52-11ea-977e-c48a38c61a92.png)

**Comment by abneetwats24** [comment]
Is there any documentation for special data types. Such as openRPA.Elis.Rossum.Queues[]
"The custom ones."
BTW Thank you problem resolved.

**Comment by skadefro** [comment]
Not right now, but you can just set a breakpoint and easily inspect it
Select an activity, press F9 to set breakpoint
![image](https://user-images.githubusercontent.com/4155937/77636943-24e34980-6f55-11ea-8d05-2c0c26a2ece9.png)
Then run the workflow, and you will be able inspect all where the property inspector is
![image](https://user-images.githubusercontent.com/4155937/77637095-670c8b00-6f55-11ea-9f83-26f0fd095058.png)

**Comment by abneetwats24** [comment]
I am unable to get the data, till file upload it is working very well then it just finished with null ExportResult. Also I am getting permission denied in node-red login with saml.
Can you help @skadefro on this.

**Comment by skadefro** [comment]
You have to wait on rossum to complete the scanning ( and complete it your self, if it didn't not recognise the invoice ) ... that is what WaitForFileStatus is for .. 
![image](https://user-images.githubusercontent.com/4155937/77667916-1449c800-6f83-11ea-8ad5-f43552149ed3.png)

**Comment by skadefro** [comment]
[rpa4-UploadAndProcessClean.zip](https://github.com/open-rpa/openrpa/files/4388967/rpa4-UploadAndProcessClean.zip)
This is one half the the RPA challlenge, for invoce scanning.

**Comment by abneetwats24** [comment]
Thank You. I got it, I did not changed the default timeout in WaitForFileStatus. That is why it was finished before my verification.
Where do I find RPA challenge to practice and get used to with openRPA.
Also can you comment why I am getting Permission Denied for node-red. Do I need to install some dependencies?

**Comment by skadefro** [comment]
I don't know, where do you get permission denied ? (screenshot/movie or can you show me using teamviewer ? Contact me on slack if you want to set up a session )

**Comment by skadefro** [comment]
Oh, and you can find the [rpachallenge here](http://www.rpachallenge.com/).

**Comment by skadefro** [comment]
The permission denied issue is fixed now .... Thank you for letting me know :-)
