### ISSUE TITLE
Not able to register on https://academy.openrpa.dk/

### ISSUE THREAD

**Issue by NaagAI** [open-rpa/openrpa#256]
Hi Team,
Attempted to create a new account on https://academy.openrpa.dk/ but it says an email is sent to registered email id with details but not received the email. Waiting for 20-30 mins but still no receipt.
Can you please help?

**Comment by skadefro** [comment]
Hu NaggAI, the academy is not really ready or open for the public. But I've manually confirmed your user account if you want to have a look around

**Comment by NaagAI** [comment]
Thank you Allan for the quick response.

**Comment by Gokuzilla** [comment]
Good afternoon!

It could release the official mrc.official user.

We would like to know the contents of the tool
