### ISSUE TITLE
Start workflow from middle

### ISSUE THREAD

**Issue by PhilipeTakeo** [open-rpa/openrpa#258]
Is possible to start the workflow from middle?

I know there is "comment out" to disable some especifield action, but if i have a huge workflow or sequence, and i have an error, everytime i need to begin from the start to test again.

So, i would like to start from the middle of the workflow.

How can I handle with this?

Thanks

**Comment by skadefro** [comment]
It has been a long time dream of mine to be able to support this, and i thought it would be impossible, but a few weeks ago, I saw one of the commercial products add support for this.
I've had a loot at how they did it, and it will require me to rewrite **alot** of code to be able to do the same. I will add this at some point but for now it will have to wait a bit.
The way most people handle this is you create a flow chart and add many sequences, 
![image](https://user-images.githubusercontent.com/4155937/77775838-68b97a00-704d-11ea-82b4-8b6f9cf0c05e.png)
And then if you want to "move down" you just change the start node 
![image](https://user-images.githubusercontent.com/4155937/77775884-7a028680-704d-11ea-8e97-d0ba323653df.png)

**Comment by PhilipeTakeo** [comment]
Thanks Allan, now i'm using flowchart.

**Comment by skadefro** [comment]
I'm adding this as a Future Project, and closing the issue. It's a massive task to get implemented, really good idea, I do want to implement it, but will have to wait a while.

**Comment by IvanGordeyev** [comment]
Out of interest. 
Could this just be just an exact copy of the code with all variables, copied as a new script/robot and then a run outside in a new window/instance, hence would the code need to be rewritten significantly? Save a new file with only code from the point of selection + variables and then run?

**Comment by skadefro** [comment]
That would be rather simple to do, but i have no idea how to "hack" the debugger to then show where in the workflow we are, when/if single stepping through the code (or and error happens). 
A solution to that, could be to just copy it to a new workflow, open a new designer, and then debug that, but that feels very hackish and far from the intent of what @PhilipeTakeo was asking for. ( but close to another feature quest i got, that's in my backlog. Adding support for creating a new workflow from a sequence by right clicking it. )

**Comment by PhilipeTakeo** [comment]
I have no problem with this anymore.
When i have an error i copy the sequence to a new workflow and do my tests there.

And I've used a lot of flowcharts since Allan commented.
