### ISSUE TITLE
Inquire how to use offline

### ISSUE THREAD

**Issue by oldesec** [open-rpa/openrpa#260]
Hi.

I downloaded and installed the program.

"https://github.com/open-rpa/openrpa/releases/download/1.0.88/OpenRPA.exe"

and using a closed network.

When run the "OpenRPA.exe" file, a login window will appear.

When close the login window, the program is terminated.

Thanks

**Comment by skadefro** [comment]
I've added a page to the [wiki](https://github.com/open-rpa/openrpa/wiki) explaining this [here](https://github.com/open-rpa/openrpa/blob/master/docs/pages/offline.md).
