### ISSUE TITLE
Open Flow setup

### ISSUE THREAD

**Issue by Josue0341** [open-rpa/openrpa#272]
I downloaded and played with OpenRPA and really like it.
Do you have a setup guide for OpenRPA and a self hosted openflow instance? If not, can I pay you to put one together over the next few days?
I really like where this project is going and I'd like to see some more tutorials as well. I might put some together myself once I'm more familiar with it.

Thanks

**Comment by skadefro** [comment]
Setup guide for OpenRPA? What kind guidence where you looking for?
For a test setup of OpenFlow, you can use docker-compose
Install [docker](https://docs.docker.com/get-docker/)
if on linx/mac also install docker-compose
if on windows, make sure docker is running in linux mode
download [docker-compose](https://github.com/open-rpa/openflow/blob/master/docker-compose-traefik.yml) as docker-compose.yaml and modify the url's to fit your setup,
Then open a shell and cd to the docker-compose.yam file and type
docker-compose up

**Comment by Josue0341** [comment]
I already installed OpenRPA, but it connects to the demo openflow. I'd like to have my own openflow instance that it connects to. I'll try docker-compose as you mentioned.
Thanks
