### ISSUE TITLE
ElementNotFound being mistakenly returned

### ISSUE THREAD

**Issue by Pestitschek** [open-rpa/openrpa#287]
I have a Workflow that starts with
1. Open Application (Chrome),
2. Go to URL
3. Click an element/button.

The button is fully loaded & available, but OpenRPA can not click it (tried both virtual/animate click on & off) and the error "Interfaces.ElementNotFound" is returned.

While trying to debug the error further, I discovered that by inserting a DoWhile box and if I (manually) move the mouse by 1 pixel OR make a TypeText("{any_button}"), the button is "suddenly" found & OpenRPA proceeds with the click (100% fix)

Then, with further debugging, I also discovered that this issue happens way more frequently when option "Minimize" turned off (turning the option on results in a 85%~ fix)

Occurrence chance while duplicating the bug was 100%. I can share the workflow with you if need be.

**Comment by skadefro** [comment]
I would like to see that workflow.

**Comment by skadefro** [comment]
Thank you for letting me access the workflow. If i understand it correctly we found that updating to latest version fixed this issue ?

**Comment by Pestitschek** [comment]
Updating to lastest version ("after your chrome/NM rework") fixed the issue.
"Wait until ready" works fine!

Closing this. Thank you!
