### ISSUE TITLE
How to save a Excel sheet

### ISSUE THREAD

**Issue by Hontor35** [open-rpa/openrpa#292]
Hello,

In toolbox, I don't find activity to save a Excel sheet. I try to do this with record button, but that don't work : 

>  OpenRPA.Interfaces.ElementNotFoundException: Failed locating 1 item(s)
>    à OpenRPA.Windows.GetElement.Execute(NativeActivityContext context)
>    à System.Activities.NativeActivity.InternalExecute(ActivityInstance instance, ActivityExecutor executor, BookmarkManager bookmarkManager)
>    à System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation)

Do you have an other solution to do this action?

**Comment by skadefro** [comment]
Github is for bug's, please use slack for usage questions.
You should be using the office activities, specifically you need to use office.Close Workbook to save
