### ISSUE TITLE
Uncomment inside Foreach Datarow rearranges workflow

### ISSUE THREAD

**Issue by Infocalyps** [open-rpa/openrpa#293]
Hi
When I Uncomment a sequence inside Foreach Datarow, the order of the elements is rearranged in the entire workflow. I have reproduced this in a sample workflow that is attached.
Tested on the latest version as of writing this. Version 1.0.105.0

**Before Uncomment**
![Before uncomment](https://user-images.githubusercontent.com/64484429/80507121-00202e80-8966-11ea-9273-33b66b00487a.png)

**After Uncomment**
![After uncomment](https://user-images.githubusercontent.com/64484429/80507132-04e4e280-8966-11ea-889c-498e13b46fd2.png)

Attached workflow
[Sample workflow.zip](https://github.com/open-rpa/openrpa/files/4546909/Sample.workflow.zip)

**Comment by skadefro** [comment]
So comment out, was only support to be used inside a sequence:
If i mark the two InvokeOpenflow and choose "Comment out" it move the two acitivites into a new seqence, inside a comment out activity as expected, and i can uncomment without issues
If i mark only on invokeopenflow and choose "Comment out", it places it inside a comment out, and i can uncomment without issues as well

So my guess is you doing something that was never meant to work (but you currently can do, do to a lag of testing for parent sequence's )
your are right clicking the sequence and trying to un comment that, and yes, that will not work
I will see if i can implement some better testing to grey out "comment out" if the activity is not already placed inside a sequence.

**Comment by Infocalyps** [comment]
Thank you, I will use the correct way to do it next time.
I am very good at doing things I can do but shouldn't :-)

You could add this text to the wiki [https://openrpa.openrpa.dk/pages/activities]
`To Comment out multiple activites:
Mark the activities and choose "Comment out" 
This will move the two activities into a new sequence that can later be "Uncommented"`

so newbies like myself does not swamp you with basic questions. I am really impressed with what OpenRPA can do and look forward to trying it out more.

**Comment by skadefro** [comment]
And thank you for that, I must admit, I'm not good at always testing all possibilities, so is glad you let me know.
Thank you, I've added the text you suggested, it will be visible next time i do a push

**Comment by skadefro** [comment]
I added support for commenting and uncommenting something not directly in a sequence. 
I've tried testing all combinations i can think of, but knowing my testing skills, i wouldn't be surprised if i missed something. Give it a try and see if this fixes your issue

**Comment by skadefro** [comment]
I'm going to assume this is fixed now. Feel free to reopen this, if you don't agree
