### ISSUE TITLE
Saving workflow throw error

### ISSUE THREAD

**Issue by harisankarreddy1210** [open-rpa/openrpa#303]
Hi team,
save work flow throw error.

work flow designer encounter with problem.
![error](https://user-images.githubusercontent.com/48940879/80918598-70261e80-8d83-11ea-9593-0dea4e53d515.PNG)
![Captureopenurl](https://user-images.githubusercontent.com/48940879/80918606-7f0cd100-8d83-11ea-8024-8fc4f7c4c011.PNG)

**Comment by skadefro** [comment]
Try and download and install .net runtime 4.7.2
https://dotnet.microsoft.com/download/dotnet-framework/net472

**Comment by skadefro** [comment]
I'm assuming this was resolved from the lack of response. Feel free to reply here, if you still have issues
