### ISSUE TITLE
[Windows Element Selector] json not created after finding an element.

### ISSUE THREAD

**Issue by Gyunstorys** [open-rpa/openrpa#306]
It worked fine in the old version.
However, there is a problem after updating to the latest version.

As shown in the image below, json is not displayed.

![image](https://user-images.githubusercontent.com/15137148/81390122-e648cd80-9155-11ea-8086-7043b7f83fc3.png)

**Comment by skadefro** [comment]
As already pointed out in #305 iframes is not supported in IE

**Comment by Gyunstorys** [comment]
> As already pointed out in #305 iframes is not supported in IE

This is not an IE element selector, but a problem with the window element selector.
The screenshot is a sample page and the windows element has been doing well so far.
And the same problem occurs everywhere other than the iframe.

**Comment by skadefro** [comment]
Ahhh ... Sorry, I completely misunderstood
I will see if i can reproduce this ( tomorrow, I'm fully booked today )

**Comment by skadefro** [comment]
Hey, sorry for the long delay.
I've just tested with the latest version of the robot. I added a Get Element from both windows, NM and IE ... right clicked and selected a few different elements, and for all 3 it worked.
Can you make a short description of how to reproduce this bug ?

**Comment by Gyunstorys** [comment]
1. 
I dropdown get element(windows) in workspace.
![image](https://user-images.githubusercontent.com/15137148/81916955-8481db00-960f-11ea-8fa0-8e3a0c694e5e.png)
2. click Open Selector button
3. click Select button
4. right button click

Then
The path of the element is well found.
![image](https://user-images.githubusercontent.com/15137148/81917159-cc086700-960f-11ea-8e57-3e9a00150953.png)

But Json is not created
![image](https://user-images.githubusercontent.com/15137148/81917320-02de7d00-9610-11ea-9b51-4da412b2088b.png)

**Comment by skadefro** [comment]
Your right, weird ... I’ll look into this

**Comment by skadefro** [comment]
Thank you for finding and reporting this. This is fixed in [latest version](https://github.com/open-rpa/openrpa/releases/download/1.0.117/OpenRPA.msi)

**Comment by Gyunstorys** [comment]
Oh! 
thx. It works fine!
