### ISSUE TITLE
for java application，can't get the cell inside a table

### ISSUE THREAD

**Issue by fjwgrace** [open-rpa/openrpa#307]
for jave application,we can get the table's width,height,location,and highlight the element ,but the cell inside the table ,we can't get it ,when detect the element  by mouse ,It just can highlight the table,not the cell inside the table ,so ,do you know how to solve it ?

**Comment by skadefro** [comment]
No sorry, not without an example to test it on. If you don't have that, maybe you'll get an solution by the [owners](https://github.com/google/access-bridge-explorer) on your ticket there.

**Comment by skadefro** [comment]
Any news ? Do you have an example i can test this issue on,

**Comment by skadefro** [comment]
I'm assuming you found another solution, and is closing this.
