### ISSUE TITLE
Installation OpenRPA complete but UI does not load...

### ISSUE THREAD

**Issue by gesvin** [open-rpa/openrpa#312]
Hello, I am installing OpenRPA for the first time, but when I run OpenRPA.exe the messages "loading plugins" and "demo ..." appear, but then nothing happens, it's as if the program starts and ends without loading the UI.
- I have Windows 8.1, Firefox 76.0.1, Python 3.8.2, JRE-8u251-windows-x64 and NDP48-web installed
- I downloaded the latest msi. OpenRPA since. ".. openrpa / releases"
- The installation of the .msi completes without problems.
- I run the Updater that comes with the .msi and update the packages without problems.
- I already tried to rename "openrpa.script.dll" to "openrpa.script.dll.old"
- "https://demo1.openrpa.dk" loads without problems in my browser.
Can you please help me?

**Comment by skadefro** [comment]
I would really like to see that, can we do a teamviewer session in about 2 hours ? 
( I'm heading for another meeting right now)

**Comment by gesvin** [comment]
Hello,
Of course, the problem is that I don't speak much English and we work with windows in Spanish. I can get someone to help us with the translation.
Do you think it's OK?

**Comment by skadefro** [comment]
If you can find a time where i can get access, you can book it directly in my calender here https://calendly.com/openrpa/60min 
Don't worry, we don't need to speak a lot if you don't want to ... :-) It's just much faster for me, to click around and check logs myself, than trying to explain my troubleshooting steps.

**Comment by skadefro** [comment]
So we located the problem. Turns out, the robot requires you to install the 64 bit version of [c++ runtime 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) to work.
Thank you, gesvin, for letting me troubleshoot this on your machine.

**Comment by gesvin** [comment]
Thanks!
