### ISSUE TITLE
Get Pixel Color

### ISSUE THREAD

**Issue by michielalbracht** [open-rpa/openrpa#314]
I'm looking for a function that returns the color at a mouse position (x and y). Is this possible?

**Comment by skadefro** [comment]
Yes. What would be a case where that is needed ?

**Comment by michielalbracht** [comment]
I need to test whether a certain action causes a pixel (with some known coordinates) to change to a given color. This must be based on pixel positions since the used GUI is pixel based.

**Comment by skadefro** [comment]
Please download latest version and see if the new Get Color activity in the Image namespace solves your request ?
To get relative coordinates, use Get Element from on of the namespaces and use the item as the Element parameter to GetColor ... alternatively you can leave Element blank and give the coordinates of the screen (from first desktop)

**Comment by skadefro** [comment]
And [here an example](https://github.com/open-rpa/examples-files/tree/master/get-web-colors) of usage

**Comment by michielalbracht** [comment]
Thank you so much for the fast response, fixing it and even providing an example.

**Comment by michielalbracht** [comment]
x and y positions cannot be variables. I'd like to fill in VB code here (or at least a variable name)

**Comment by skadefro** [comment]
[Latest](https://github.com/open-rpa/openrpa/releases/latest/download/OpenRPA.msi) version of the robot now allows you to use variables as input for offset x and offset y.
