### ISSUE TITLE
GetMail Unread not working 

### ISSUE THREAD

**Issue by arasumiyan** [open-rpa/openrpa#321]
The GetMail Unread mail is not working- When I set UnreadOnly  true/false same email count getting 
 and Move email item also not working . Please let me know how to proceed on this . Thanks

**Comment by skadefro** [comment]
A reproducable workflow would help.

**Comment by arasumiyan** [comment]
I'm sorry. I did not understand. Please elaborate

> A reproducable workflow would help.

**Comment by skadefro** [comment]
Create a simple workflow that shows the bug, export it and upload here, so i can see the bug

**Comment by arasumiyan** [comment]
Thanks for fast response @skadefro. Now its working fine both Unreadmail /move email after closed/reopened my OpenRPA.

**Comment by skadefro** [comment]
Good to hear. Closing since is solved.
