### ISSUE TITLE
How to do Web page Table Extraction to DataTable ?

### ISSUE THREAD

**Issue by arasumiyan** [open-rpa/openrpa#322]
I tried to extract the Webpage Table data to DataTable but I can get the item.Value as String. is there any way to push the item value to DataTable ? Please let me know. I have attached Sample input files and xmal file also. Thanks[DataExtraction.zip](https://github.com/open-rpa/openrpa/files/4695486/DataExtraction.zip)

**Comment by skadefro** [comment]
Can i please ask you to use slack for usage auestions. Github is for bugs only.

**Comment by skadefro** [comment]
Really good example in the zip ! .. thank you making it clean and easy to test
While going through it, I found a bug in the IE selector parsing.
So please upgrade to [latest beta version](https://github.com/open-rpa/openrpa/releases/tag/1.0.121-beta2) of the robot, and then look at the following workflow. This will show you how data extraction was meant to work 
[DataExtraction.zip](https://github.com/open-rpa/openrpa/files/4695950/DataExtraction.zip)

**Comment by arasumiyan** [comment]
Hi Allan,
I used split regex(\n\s+) with while loop to push the string  to data-table. Thanks for the update . I will upgrade latest beta version and check .  How to ask  question in slack Please clarify details.

Do you have any activities like HTTP, SOAP?
Regards,
Arasu

**Comment by arasumiyan** [comment]
> Hi Allan,
> I used split regex(\n\s+) with while loop to push the string to data-table. Thanks for the update . I will upgrade latest beta version and check . How to ask question in slack Please clarify details.
> 
> Do you have any activities like HTTP, SOAP?
> Regards,
> Arasu

If i upgrade it will affect  my current code ?

**Comment by skadefro** [comment]
You can join openrpa's [#slack here](https://slack.openrpa.dk/) 
That is what OpenFlow is for, click OpenFlow in the robot and go to the NodeRED tab, and click create ... wait some seconds then click the nodered button and login, you will find anything easy drag and drop access to to more than 2500 api's and several nodes for talking with custom api's as well.

**Comment by arasumiyan** [comment]
I joined Slack - where to raise the question- sorry its new for me

when i openflow from openRPA studio . I am getting blank screen with menus only. attache for reference.
  
![openFlowMenu](https://user-images.githubusercontent.com/66029174/83243625-d011b880-a1bb-11ea-89b9-c9f092fd3dba.PNG)

**Comment by skadefro** [comment]
You need to use chrome, firefox or the new edge browser. Internet explorer is not supported on the webpage. Just copy the url over to one of those.

**Comment by arasumiyan** [comment]
I used chrome and able to see my workflows.  Is there anyway to execute my workflow through openflow or Node-RED?

**Comment by skadefro** [comment]
Can we please use slack for support ? Github is only for bugs.
Yes, you can control robots from both openflow and nodered.

**Comment by skadefro** [comment]
Assuming this is solved, please reopen if needed or contact us on rocket chat
