### ISSUE TITLE
How to perform dynamic pdf scraping

### ISSUE THREAD

**Issue by cooolguyselva** [open-rpa/openrpa#335]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, firefox, edge, id]

**Workflow (please complete the following information):**
 - Create a simple workflow that reproduces the error so we can test this locally.

**Additional context**

**Comment by skadefro** [comment]
Not a bug, use rocket chat for usage questions
