### ISSUE TITLE
OpenRPA.IE.Browser contructor seems to not use the parameter

### ISSUE THREAD

**Issue by Dmitry-Me** [open-rpa/openrpa#336]
I've annotated code of `OpenRPA.IE.Browser` constructor...

        public Browser(AutomationElement Element) // Element is the parameter...
        {
            var HWNDs = new Dictionary<Int32, AutomationElement>();
            // Here Element is used to initialize ele and it's not used anywhere else
            var ele = Element;
            while (ele != null)
            {
                if (ele.Properties.NativeWindowHandle.IsSupported)
                {
                    var HWND = ele.Properties.NativeWindowHandle.Value.ToInt32();
                    HWNDs.Add(HWND, ele);
                }
                ele = ele.Parent;
            }
            // the loop above traverses the automation elements until it finds the
            // topmost one and fills a dictionary but the dictionary is not used after this loop
            findBrowser();
            if (wBrowser.Document == null) throw new Exception("Failed initializing Internet Eexplorer");
            Document = wBrowser.Document as MSHTML.HTMLDocument;
            title = Document.title;
        }

so what I see is `Element` parameter is used to run a loop which causes a dictionary to be built and the dictionary is not used after that. Isn't the parameter useless?

**Comment by skadefro** [comment]
That does look weird, agree ... I'll clean that up soon.

**Comment by skadefro** [comment]
Thank you for bringing my attention to this
