### ISSUE TITLE
Package Manager is blank

### ISSUE THREAD

**Issue by pmt-iwata** [open-rpa/openrpa#345]
I started "OpenRPA Package Manager", but no packages are dispayed.

![image](https://user-images.githubusercontent.com/57798679/86223582-b3a1db00-bbc2-11ea-8976-16bbaca72e8e.png)

Do I need to config anything?

**Comment by skadefro** [comment]
It's there for legacy, a new version will be coming in near future.

**Comment by pmt-iwata** [comment]
thank you.
