### ISSUE TITLE
Exception occurs because the initial value of workflow name is invalid

### ISSUE THREAD

**Issue by pmt-iwata** [open-rpa/openrpa#350]
Hi.

When you create a new workflow, it will be created with the name "New Workflow".
An exception occurs if you create an argument without changing the workflow name and enter the default value, and save.

Probably because it is converted to the code "New Workflow.CREATED_ARGUMENT_NAME = DEFAULT_VALUE".
How about changing the initial value of the workflow name or separating with "_" ?

![image](https://user-images.githubusercontent.com/57798679/87028670-e7f84580-c219-11ea-89db-ee5b70291b21.png)
![image](https://user-images.githubusercontent.com/57798679/87028699-f6466180-c219-11ea-9f10-6c44778b114f.png)

**Comment by skadefro** [comment]
Nice catch, thank you. I'll push a fix for that right now

**Comment by skadefro** [comment]
done.
