### ISSUE TITLE
Working with RadioButtons & CheckBoxes

### ISSUE THREAD

**Issue by rayanaravikumar** [open-rpa/openrpa#353]
Hi,
I have created a sample c# windows forms application with text box,radio buttons,check boxes,combo boxes,list box and trying to automate the processing like reading the data from CSV file and fill the details in c# application.

1. Followed the "mycrm-readandfill" example and could read the data from CSV file and fill in text boxes, combo boxes and list boxes, but facing the problem while select / de-select radio buttons & check boxes.

2. For example i have --> Gender : Male & Female radio buttons, Skills --> C# , Java, Python check boxes

Could you please help me how to fill these controls data based on my data in CSV file.

**Comment by skadefro** [comment]
Please use rocket chat for usage questions ... this is only for bug reports.
