### ISSUE TITLE
OpenRPA.exe quarantined by Bitdefender with Atc4.Detection Malware - false positive ?

### ISSUE THREAD

**Issue by beradeng** [open-rpa/openrpa#354]
**Describe the bug**
First time download and install of OpenRPA on Win10 with current Bitdefender installation. First start of OpenRPA was intercepted by Bitdefender. 
Is this a false positive ?

**Comment by skadefro** [comment]
The technology used for doing RPA is not "normal" and I could understand why some AV vendors would mark that as suspicious. 
A quick test of the latest version does however, not give any hits/false hits 
https://www.virustotal.com/gui/file/a2539deb75c831fabaa55874bf438c68d842d7a57e98201b95269071714ac315/detection
