### ISSUE TITLE
"Workflow Designer encountered problem with your document" occured during save "New Workflow"

### ISSUE THREAD

**Issue by tomleetv** [open-rpa/openrpa#356]
**Describe the bug**
"Workflow Designer encountered problem with your document" occured during save "New Workflow"

**To Reproduce**

OpenRPA: 1.0.135
OpenFlow: 0.0.575

1.OpenRPA run
2.click "New" Button and New Workflow ("New Workflow" will be created)
3.click "Arguments" tab and click "Name" row.(argument1 is default)
4.click "Default value" and type "1" in the it's value.
5.click "Save" Button.
6.the issue occurs
(if the workflow name is changed (ex. New Workflow -> NewWorkflow) this issue is not occured.)

Expected behavior
done save with no problem.

Screenshots
N/A

Desktop (please complete the following information):

OS: [Windows 10 Pro]
Browser [chrome]
Version [1.0.135.0]
Workflow (please complete the following information):
N/A

Additional context
N/A

**Comment by skadefro** [comment]
This should have been fixed a few versions ago, please upgrade to [latest version](https://github.com/open-rpa/openrpa/releases/latest/download/OpenRPA.msi) and see if that fixes your problem ?

**Comment by tomleetv** [comment]
Thanks! skadefro. this issue is not reproduced on latest version (1.0.141)
