### ISSUE TITLE
Wait For Download - new feature

### ISSUE THREAD

**Issue by manashk** [open-rpa/openrpa#358]
Hi Allan,
It would be great for everyone if we have an activity to wait for download and move it to a specified folder, post download completes. basically where there is no url to specify the download, Download starts with clicking a buttor, or export button. It would be great activity to report automation where the RPA developer has to download reports from any CRM or ERP.

**Activity should have the following Inputs.**

1. File extension - example ".csv". we can specify the patern as well like "report*.csv", keeping blank will assume "*.*"
2. Download Folder -  if blank, the Downloads folder of the current user will be used, if other than download path is specified in the browser, that needs to be put here.
3. Download Time - if blank, the current DateTime will be used. user can save the datetime in a variable before the click activity of the export or download button and put the DateTime variable here.
4. Timeout - in milliseconds, default 30000, wait for the file to download before an error is thrown. 
5. Delay - in milliseconds, default 1000. delay of time to loop to search the file. 
6. Move to - the path to move the downloaded file to. if not specified, file will be in the downloaded folder only.
7. Rename - if specified, remane the file after download.

**Activity should have the following Output.**

File name - The full path with the file name. if **Move to** folder specified then fullpath name will have the move to folder path instead downoad folder path. if **Rename** specified, file name would have the renamed file.

**Comment by skadefro** [comment]
Good idea

**Comment by skadefro** [comment]
So to avoid messing too much with peoples browser experience i made a scaled down version of your suggestion.
I added a new WaitForDownload activity, this will trigger when the next download has completed in your browser ( only testet with chrome right now) and you can set a timeout, to avoid it hanging for ever, incase the download fails or never completes.
As a side effect, there is now a download detector in the robot, so you can trigger a workflow every time a user downloads a file.
![image](https://user-images.githubusercontent.com/4155937/88785521-96e0cf00-d191-11ea-876c-6dea6c5bc49d.png)

**Comment by skadefro** [comment]
Now confirmed to work for firefox and edge as well
