### ISSUE TITLE
Open file dialog box - get element issue

### ISSUE THREAD

**Issue by manashk** [open-rpa/openrpa#360]
Hi Allan,
the nm getelement and windows getelement both fail to typetext or assign in the open dialog box file name field and click open button. though worked 1-2 times but fails when tabs changes with different webpages.

![image](https://user-images.githubusercontent.com/68864590/88735312-538d4e80-d106-11ea-966f-0f5a1a4a981a.png)

[test.zip](https://github.com/open-rpa/openrpa/files/4991619/test.zip)

**Comment by skadefro** [comment]
Sorry for the long delay. 
I cannot reproduce this, i made a simple example where i uploaded 10 different files but navigate away before uploading each file, and had no issues at all.
But i finally made it easier to select windows element inside chrome/edge that is not a webpage item, like the select file dialog or popup dialogs (alert/input)

**Comment by manashk** [comment]
Thanks Allan, Let me check.

**Comment by skadefro** [comment]
did you get a chance to check it ?

**Comment by skadefro** [comment]
Hey, I'm going to assume this works, if not, please reopen this issue or create a new one.
