### ISSUE TITLE
Right-click "Comment out" will cause infinite activity boxes or crash

### ISSUE THREAD

**Issue by Ghitafjorback** [open-rpa/openrpa#372]
**Describe the bug**
If I right-click a sequence and choose to "comment out", a ton of commented out boxes will appear, and often the program will crash.

**To Reproduce**
1. Right-click a "Sequence"
2. Click on "Comment out"
3. See error

**Expected behavior**
I expected it to "comment out" the sequence

**Screenshots**
![image](https://user-images.githubusercontent.com/59295827/89909135-05407b00-dbef-11ea-81a4-fbb4f0e0f156.png)

**Desktop (please complete the following information):**
 - OS: Win10
- OpenRPA version: 1.0.152

**Comment by skadefro** [comment]
This has been fixed in latest version
