### ISSUE TITLE
Language Settings

### ISSUE THREAD

**Issue by fraefel** [open-rpa/openrpa#374]
After changing the UI Language to English (from Danish) and restarting OpenRPA, in the lower left corner it still says "Værktøjskasse", "Logning" and "Udskrift"

![image](https://user-images.githubusercontent.com/4086560/90147211-3e5d2480-dd82-11ea-9658-70f34734e191.png)

![image](https://user-images.githubusercontent.com/4086560/90147028-08b83b80-dd82-11ea-8205-ad40af94aaee.png)

- Windows 10 Danish UI

Running build 153.

**Comment by skadefro** [comment]
When you change language, to robot delete C:\Users\<user>\Documents\OpenRPA\layout.config and expects you to close the robot right after, maybe something went wrong for you ?
Try closing the robot, delete C:\Users\<user>\Documents\OpenRPA\layout.config then it should be completely reset again

**Comment by skadefro** [comment]
hm, turns out i did not test this properly.
if you do NOT have an layout file, the robot would save a layout in the wrong language, and then you would experience what you just saw. thank you for pointing out this bug.

**Comment by skadefro** [comment]
This has been fixed in latest version
