### ISSUE TITLE
Unable to Lauch OpenRPA

### ISSUE THREAD

**Issue by agalino91** [open-rpa/openrpa#380]
**Describe the bug**
I have successfully installed openRPA. I am able to open it but it stops at the Login Box. There is no display at all and it just keeps loading... Any help would be greatly appreciated.

**Comment by skadefro** [comment]
Does it show the login screen?
Or where in the process does it keep loading?
What message is the last message it shows?
Did you install the java extension or did you leave all default?

**Comment by agalino91** [comment]
> Does it show the login screen?
> Or where in the process does it keep loading?
> What message is the last message it shows?
> Did you install the java extension or did you leave all default?

it shows the login screen but there are no texts inside. I did not install the java extension and I'm just using the default.

**Comment by skadefro** [comment]
I just tried with a fresh robot, i cannot login with a new user. Thank you for letting me know, ill look into this asap

**Comment by skadefro** [comment]
As a work around you can try [offline](https://openrpa.openrpa.dk/pages/offline) until i get it fixed,

**Comment by agalino91** [comment]
> As a work around you can try [offline](https://openrpa.openrpa.dk/pages/offline) until i get it fixed,

Thank you so much for your prompt response. :) I'll be following. :)

**Comment by skadefro** [comment]
The dialog died out on rocket. Feel free to reach out again on rocket chat, so we can try attaching a debugger as we discussed.
