### ISSUE TITLE
Request version 1.1 (or above) Release : Need latest 1.0 version to make short tech notes.

### ISSUE THREAD

**Issue by igapyon** [open-rpa/openrpa#409]
**Describe the bug**
Feature Request: Named Version 1.1 (or above) release.
I am going to write short tech notes regarding OpenRPA.
Around writing notes, I hope OpenRPA will release version 1.1 (or above), It means there is latest OpenRPA 1.0 version. and I will be able to write tech notes against Version 1.0.

**Comment by skadefro** [comment]
I'm not sure I understand the reason behind this ? Can you elaborate a little more ?

**Comment by igapyon** [comment]
I think some of beginners will be confused by small difference between tutorial screenshot and the real application.
It might be happen for first step of beginner.
So I want the frozen version of OpenRPA to write tutorial document.

**Comment by skadefro** [comment]
That makes sense. I'm not quite ready to "lock it in" but I will try and make that happen soon, and then roll over to version 1.1

**Comment by skadefro** [comment]
I'm flipping over to 1.1.x now.
