### ISSUE TITLE
Start Menu Typing Bug

### ISSUE THREAD

**Issue by engahmed1190** [open-rpa/openrpa#410]
**Describe the bug**

While running workflow that searches for the calculator in Start Menu.  1st letter is missing 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/25582838/93897533-785f0600-fcf2-11ea-8842-58ba02e56884.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, firefox, edge, id]

**Workflow (please complete the following information):**
 - Create a simple workflow that reproduces the error so we can test this locally.

**Additional context**

**Comment by skadefro** [comment]
This is not a bug, but a usage question. Please join rocket chat for help on how to create a workflow for that scenario ( you need to add an delay, and this is NOT the correct way to start an application, you use "Open Application" for that )
