### ISSUE TITLE
About AviRecorder

### ISSUE THREAD

**Issue by RupaliLamkhade** [open-rpa/openrpa#432]
Hello,

How I set inputs for Start Recording action. In the property panel there is **Codec** property and this is unclear for me.

Regards,
Rupali

**Comment by skadefro** [comment]
Please use [rocket chat](https://rocket.openiap.io/) for usage questions

**Comment by RupaliLamkhade** [comment]
Hello,

 
If you have any documentation support then can you share me your documents for more understanding.

 
 
Regards,

Rupali

 
-----Original message-----

**Comment by skadefro** [comment]
You can find documentation at https://github.com/open-rpa/openrpa/wiki and https://docs.openiap.io/
If you need more help, you can join the community at rocket chat https://rocket.openiap.io

**Comment by RupaliLamkhade** [comment]
Hello,

 
Thanks, I'll go through this links ad if I have any problem then I'll  inform you.

 
 
Regards,

Rupali

 
 
-----Original message-----

**Comment by skadefro** [comment]
No, don*t inform me, go to rocket chat, if you need more help. ( or you can sign up for a support agreement :-) )
