### ISSUE TITLE
Help, How to build from source?

### ISSUE THREAD

**Issue by Dylan072** [open-rpa/openrpa#442]
**Build from source**
System: Windows 10 x64 with VS 2019

**Comment by Dylan072** [comment]
`<Reference Include="System.Management.Automation">
      <HintPath>..\..\..\Windows\assembly\GAC_MSIL\System.Management.Automation\1.0.0.0__31bf3856ad364e35\System.Management.Automation.dll</HintPath>
    </Reference>
    <Reference Include="System.Xaml" />`

**Comment by skadefro** [comment]
Please use [rocket](https://rocket.openiap.io/) for usage questions.
