### ISSUE TITLE
Can I parse argument from command line?

### ISSUE THREAD

**Issue by chaweewatp** [open-rpa/openrpa#449]
I try to run the workflow from the command line with the input argument.
eg. > OpenRPA.exe /Workflowid dev\UpdateData.xaml -userid "02"

But the result doesn't work. 
the argument and variable have only a default value.

**Comment by skadefro** [comment]
Please use [rocket chat](https://rocket.openiap.io/) or [forum](https://bb.openiap.io/) for usage questions
