### ISSUE TITLE
the java bridge mechanism?

### ISSUE THREAD

**Issue by thicongtu2** [open-rpa/openrpa#52]
i 'm interested on writing a program that automation for the java application, and work with jab.
i know the jab need a window for working. but i dont know, when it can work, after i launch java application or before... 
I write a win-form application, i launch java app in this constructor, and write the automation script(click a button in java application) inside a callback function of a win-form 's button.
the first click, nothing play, the next time is play, i can explain how it was.
very nice for hearing from you.

**Comment by skadefro** [comment]
This forum should be used for OpenRPA questions.
But I will try and answer your questions:
I think the reason your first click doesn't work is you haven't waited for jab to initialize.
You do not need to launch java from the windows application, you can start java both before and after you started your windows application. 
I recommend you take a look at https://github.com/jdog3/JavaAccessBridge.Net-Sample or https://github.com/google/access-bridge-explorer

**Comment by thicongtu2** [comment]
> I think the reason your first click doesn't work is you haven't waited for jab to initialize.
i tried with: 
```var jab = new JavaAccessBridge();
 jab.Initialize();
 Thread.Sleep(2000);
// do action with java app
```
but it not work...

**Comment by skadefro** [comment]
Then i don't know what your problem is, try and create a simpel example and publish on github i will take a look.
I'm going to close this issue, it has nothing to do with OpenRPA, but feel fee to post an URL in this thread.

**Comment by thicongtu2** [comment]
here is my repository i 've push to.
https://github.com/thicongtu2/jab-problem
thank you very much

**Comment by skadefro** [comment]
Ahhh, yes, it will take a few seconds before jab can see the windows.
Try this, then "do our magic" when counts > 0 

        private AccessBridge jab = new AccessBridge();
        private System.Timers.Timer timer = new System.Timers.Timer() { Interval = 500, AutoReset = true, Enabled = true };
        private int lastCount = 0;
        public MainWindow()
        {
            InitializeComponent();
            jab.Initialize();
            timer.Elapsed += OnElapsed;
        }
        private void Find_Click(object sender, RoutedEventArgs e)
        {
            var listWindows = jab.EnumJvms();
            Console.WriteLine(listWindows.Count);
        }
        private void OnElapsed(Object source, System.Timers.ElapsedEventArgs e)
        {
            var listWindows = jab.EnumJvms();
            if(lastCount != listWindows.Count)
            {
                Console.WriteLine("New JVM count is  " + listWindows.Count);
            }
        }

**Comment by thicongtu2** [comment]
thank you very much .
but why we put `Thread.Sleep(200)` after `jab.Initialize();` it not work.

**Comment by skadefro** [comment]
You are doing the Thread.Sleep in the UI thread, so It's "locking up" the thread while doing the sleep.
So that is why we need to move the code to another thread (in my example a timer)

**Comment by thicongtu2** [comment]
> move the code to another thread (in my example a timer)
that mean i create a new thread from the MainWindow() constructor, and the automation can work without click or binding any action.

**Comment by skadefro** [comment]
yes

**Comment by thicongtu2** [comment]
yeah, it work.
thank you very much
