### ISSUE TITLE
Can't connect to wss://demo1.openrpa.dk/

### ISSUE THREAD

**Issue by winterlaite** [open-rpa/openrpa#55]
Issue: Can't connect to wss://demo1.openrpa.dk/
Platform: Win7 64 SP1
Compiled binaries: VS 2019, latest version (2019.06.14)
Description:
There were no errors in compilation, although there were numerous warnings. I copied all files to  C:\openrpa, and unblocked all dlls (even though I compiled them). I changed the permissions of the main binary to run as admin. Although it starts fine, and the GUI appears, it hangs at "connecting to wss://demo1.openrpa.dk/. I have specifically set an exception for the program in my firewall.
Thanks!

**Comment by skadefro** [comment]
Can you open https://demo1.openrpa.dk ?
wss;//demo1.openrpa.dk means connect on https ( port 443 ) to that domain, but it keeps the connection open, so proxy/reverse proxys is not supported. 

You don't need to connect to openrpa.dk, if you open settings.json and removes the URI from wsurl you can use the robot with workflows/state only saved locally.
![image](https://user-images.githubusercontent.com/4155937/59522363-ccafef00-8ece-11e9-9c55-f2b1cdb2dfb9.png)

**Comment by winterlaite** [comment]
Thanks! That did it.

**Comment by skadefro** [comment]
Should be solved now.
