### ISSUE TITLE
Cannot open or save projects/workflows

### ISSUE THREAD

**Issue by winterlaite** [open-rpa/openrpa#56]
Although I was able to create a simple workflow, clicking Save did not open a dialog, and neither did not Open. Instead, now every time I run openrpa it opens the first (and so far only) workflow I created (Project1)

A folder "Project1" was created in the program directory, but it seems to me there should be an option to select a project folder, as well as to save, open, and rename projects.

v. 0.0.330, Win 7 64-bit, compiled with VS 2019

**Comment by skadefro** [comment]
For now, the project folder is where the binaries are.
At some point I will properly split it up, so you can save either with binaries or in some part os %userprofile%.
I agree, it might not be obvious, but you name the worflow by clikcing the background to select the ActivityBuilder and then setting the name property
![image](https://user-images.githubusercontent.com/4155937/59526981-a001d480-8eda-11e9-83a6-8954fa9b2c17.png)

**Comment by winterlaite** [comment]
Thank you, that's very helpful. The renaming works fine. 

In case it might help someone else, you can switch projects from the "Open project" button on the top left of the GUI below the ribbon, after the program has loaded Worflow 1, Project 1.

Although the renaming doesn't show up right after opening a project (see first .png), clicking on the "New_Workflow" link will bring it up correctly named (see second .png). Thereafter, at least during the running session, it can be referenced from "Open project" with the correct name (see third .png).
![projects_1](https://user-images.githubusercontent.com/10135022/59528685-2ba84080-8e9c-11e9-893d-a251843d5032.PNG)
![projects_2](https://user-images.githubusercontent.com/10135022/59528710-34007b80-8e9c-11e9-96dd-1321fb2b2c55.PNG)
![projects_3](https://user-images.githubusercontent.com/10135022/59528715-3a8ef300-8e9c-11e9-847d-2c182acc1607.PNG)

**Comment by skadefro** [comment]
Was solved, but could use some improvement, will work on that soon.
