### ISSUE TITLE
login window doesn't appear

### ISSUE THREAD

**Issue by zooyf** [open-rpa/openrpa#66]
I download the https://github.com/open-rpa/openrpa/releases/download/0.0.39/OpenRPA.zip

extract to a folder. but the edit window in the video https://www.youtube.com/watch?v=SqLHlMpQhZA&feature=youtu.be doesn't show up.

So I can't do anything but asking for help.

**Comment by skadefro** [comment]
Did you unblock the files ? Windows often "blocks" files downloaded from the internet, that is why i added a unblock powershell script, but often it's enough to just unblock OpenRPA.exe
![UnBlock2](https://user-images.githubusercontent.com/4155937/60794470-29b76180-a16a-11e9-83b9-65d986c312e6.png)

**Comment by skadefro** [comment]
After some troubleshooting we located the problem.
My servers are hosted in google cloud, but China is blocking access to those. So the solution right now is to use the robot "offline" by implementing the workout mentioned in #55 .
I will try and work on a solution that will work for people i China ( for instance by hosting a copy in alibabacloud )
