### ISSUE TITLE
crash on enter text

### ISSUE THREAD

**Issue by Krogsager** [open-rpa/openrpa#68]
I'm trying to do a simple recording of a URL into my browser, when the recording stops abruptly.
![2019-07-11 12_55_58-Mozilla Firefox](https://user-images.githubusercontent.com/27994384/61045743-ba48a880-a3db-11e9-9068-f0d22662ca1b.png)

Using release 0.0.40 a

**Comment by skadefro** [comment]
Are you recording in Internet Explorer, Chrome or Firefix ?
If Chrome or Firefox, have you installed the [browser addon](https://openrpa.openrpa.dk/pages/nativemessaging) ?

**Comment by Krogsager** [comment]
I was using Firefox and did not have the plugin installed
