### ISSUE TITLE
Cannot register

### ISSUE THREAD

**Issue by burque505** [open-rpa/openrpa#77]
Although the login window appears, and the link to register opens the appropriate dialog, there appears to be no way to actually register. After submitting a username and password, there is no followup email or dialog. Trying to log in with the newly created username and password doesn't work. I can use the editor if I follow the procedure referenced in #56 though. Are there instructions somewhere for registering? I didn't find them.

**Comment by skadefro** [comment]
I see you created a user the 15th this month, but never logged in, so if you tried registering today that might given you problems. But no matter what, when ever i try to register a new user with a username already take i get this error as expected ? ( username is email, not you name )
![image](https://user-images.githubusercontent.com/4155937/61378313-6fc89f80-a8a5-11e9-9ae8-4c310503367c.png)
Don't you get that error when trying to register a new user, with an already used email ?
( The email is just to make sure names are unique, you will **not** get an email with a link to press or anything like that  )

**Comment by burque505** [comment]
I did get that error. I no longer remember the password I used and have no way to retrieve it. I have tried all the combinations I would normally use and none worked.

**Comment by skadefro** [comment]
I've deleted he user, you can register again. And i will start working on a "reset password" function

**Comment by burque505** [comment]
Thank you, this one is closed!
